import csv, re
from pathlib import Path

repo = Path('.').resolve()
csv_path = repo / 'imoveis' / 'landings.csv'

with open(csv_path, encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    existing = list(reader)

clean = []
for r in existing:
    slug = (r.get('slug') or '').strip()
    if re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', slug):
        clean.append(r)
    else:
        print('dropping_bad_slug', slug)

new_rows = [
    {
        'title': 'Apartamento 3 quartos suíte em Santos',
        'description': 'Apartamento 3 quartos suíte em Santos: vista mar, lazer completo, 2 vagas. Oportunidade na orla mais valorizada do litoral.',
        'city': 'santos',
        'type': 'apartamento',
        'slug': 'apartamento-3-quartos-suite-santos',
        'price': 'R$ 850.000–1.200.000',
        'price_raw': '900000',
        'bedrooms': '3–4',
        'area': '110–160 m²',
        'image': 'https://praia.digital/img/santos-apartamento-vista-mar.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Apartamento%203%20quartos%20su%C3%ADte%20em%20Santos&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Apartamento frente mar Guarujá',
        'description': 'Apartamento frente mar Guarujá: varanda panorâmica, piscina, academia. Oferta para quem quer vista definitiva.',
        'city': 'guaruja',
        'type': 'apartamento',
        'slug': 'apartamento-frente-mar-guaruja',
        'price': 'R$ 700.000–1.000.000',
        'price_raw': '850000',
        'bedrooms': '2–3',
        'area': '90–140 m²',
        'image': 'https://praia.digital/img/gua-casa-duplex.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Apartamento%20frente%20mar%20Guaruj%C3%A1&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Casa condomínio fechado Bertioga',
        'description': 'Casa condomínio fechado Bertioga: segurança 24h, área verde, churrasqueira. Ideal para famílias.',
        'city': 'bertioga',
        'type': 'casa',
        'slug': 'casa-condominio-bertioga',
        'price': 'R$ 650.000–980.000',
        'price_raw': '800000',
        'bedrooms': '3–4',
        'area': '130–220 m²',
        'image': 'https://praia.digital/img/berta-alto-padrao.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20na%20Casa%20condom%C3%ADnio%20fechado%20Bertioga&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Cobertura duplex Santos',
        'description': 'Cobertura duplex Santos: terraço privativo, piscina, 4 vagas. Acabamento alto padrão.',
        'city': 'santos',
        'type': 'cobertura',
        'slug': 'cobertura-duplex-santos',
        'price': 'R$ 1.100.000–1.600.000',
        'price_raw': '1300000',
        'bedrooms': '3–4',
        'area': '180–250 m²',
        'image': 'https://praia.digital/img/santos-apartamento-vista-mar.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20na%20Cobertura%20duplex%20Santos&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Studio temporada Itanhaém',
        'description': 'Studio temporada Itanhaém: investimento com alta taxa de ocupação, lazer completo e fácil acesso à praia.',
        'city': 'itanhaem',
        'type': 'studio',
        'slug': 'studio-temporada-itanhaem',
        'price': 'R$ 180.000–320.000',
        'price_raw': '250000',
        'bedrooms': '1',
        'area': '35–55 m²',
        'image': 'https://praia.digital/img/it-casa-terrea.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Studio%20temporada%20Itanha%C3%A9m&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Sobrado 3 dormitórios Mongaguá',
        'description': 'Sobrado 3 dormitórios Mongaguá: quintal, garagem coberta, proximidade com orla.',
        'city': 'mongagua',
        'type': 'sobrado',
        'slug': 'sobrado-3-dormitorios-mongagua',
        'price': 'R$ 420.000–680.000',
        'price_raw': '550000',
        'bedrooms': '3–4',
        'area': '110–160 m²',
        'image': 'https://praia.digital/img/mon-ap-compacto.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Sobrado%203%20dormit%C3%B3rios%20Mongagu%C3%A1&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Terreno plano Peruíbe',
        'description': 'Terreno plano Peruíbe: infraestrutura pronta, documentação ok, boa valorização futura.',
        'city': 'peruibe',
        'type': 'terreno',
        'slug': 'terreno-plano-peruibe',
        'price': 'R$ 150.000–280.000',
        'price_raw': '200000',
        'bedrooms': '',
        'area': '200–450 m²',
        'image': 'https://praia.digital/img/per-sobrado.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Terreno%20plano%20Peru%C3%ADbe&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Apartamento 2 quartos Praia Grande',
        'description': 'Apartamento 2 quartos Praia Grande: lazer completo, fácil acesso à via Imigrantes.',
        'city': 'praia-grande',
        'type': 'apartamento',
        'slug': 'apartamento-2-quartos-praia-grande',
        'price': 'R$ 300.000–520.000',
        'price_raw': '420000',
        'bedrooms': '2–3',
        'area': '70–110 m²',
        'image': 'https://praia.digital/img/pg-studio-moderno.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Apartamento%202%20quartos%20Praia%20Grande&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Casa vila Santos',
        'description': 'Casa vila Santos: tranquilidade, segurança, ótima localização residencial.',
        'city': 'santos',
        'type': 'casa',
        'slug': 'casa-vila-santos',
        'price': 'R$ 550.000–820.000',
        'price_raw': '700000',
        'bedrooms': '2–3',
        'area': '90–140 m²',
        'image': 'https://praia.digital/img/santos-apartamento-vista-mar.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20na%20Casa%20vila%20Santos&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Apartamento suíte vista mar São Vicente',
        'description': 'Apartamento suíte vista mar São Vicente: sacada gourmet, lazer completo e vista definitiva.',
        'city': 'sao-vicente',
        'type': 'apartamento',
        'slug': 'apartamento-suite-vista-mar-sao-vicente',
        'price': 'R$ 520.000–780.000',
        'price_raw': '650000',
        'bedrooms': '2–3',
        'area': '85–130 m²',
        'image': 'https://praia.digital/img/sv-cobertura-duplex.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Apartamento%20su%C3%ADte%20vista%20mar%20S%C3%A3o%20Vicente&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Cobertura penthouse Guarujá',
        'description': 'Cobertura penthouse Guarujá: terraço exclusivo, piscina privativa, 3 vagas. Acabamento premium.',
        'city': 'guaruja',
        'type': 'cobertura',
        'slug': 'cobertura-penthouse-guaruja',
        'price': 'R$ 980.000–1.450.000',
        'price_raw': '1200000',
        'bedrooms': '3–4',
        'area': '170–240 m²',
        'image': 'https://praia.digital/img/gua-casa-duplex.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20na%20Cobertura%20penthouse%20Guaruj%C3%A1&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Apartamento 3 quartos Bertioga',
        'description': 'Apartamento 3 quartos Bertioga: varanda, lazer completo e proximidade com natureza.',
        'city': 'bertioga',
        'type': 'apartamento',
        'slug': 'apartamento-3-quartos-bertioga',
        'price': 'R$ 480.000–720.000',
        'price_raw': '600000',
        'bedrooms': '3',
        'area': '100–150 m²',
        'image': 'https://praia.digital/img/berta-alto-padrao.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Apartamento%203%20quartos%20Bertioga&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Studio investimento Santos',
        'description': 'Studio investimento Santos: alta liquidez, fácil locação, ideal para portfolio imobiliário.',
        'city': 'santos',
        'type': 'studio',
        'slug': 'studio-investimento-santos',
        'price': 'R$ 220.000–380.000',
        'price_raw': '300000',
        'bedrooms': '1',
        'area': '28–45 m²',
        'image': 'https://praia.digital/img/santos-apartamento-vista-mar.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Studio%20investimento%20Santos&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Sobrado condomínio Itanhaém',
        'description': 'Sobrado condomínio Itanhaém: área de lazer, churrasqueira, espaço pet-friendly.',
        'city': 'itanhaem',
        'type': 'sobrado',
        'slug': 'sobrado-condominio-itanhaem',
        'price': 'R$ 560.000–850.000',
        'price_raw': '720000',
        'bedrooms': '3–4',
        'area': '130–190 m²',
        'image': 'https://praia.digital/img/it-casa-terrea.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Sobrado%20condom%C3%ADnio%20Itanha%C3%A9m&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Apartamento vista mar Santos',
        'description': 'Apartamento vista mar Santos: sacada gourmet, lazer completo, 2 vagas. Perfeito para temporada e moradia.',
        'city': 'santos',
        'type': 'apartamento',
        'slug': 'apartamento-vista-mar-santos',
        'price': 'R$ 750.000–1.100.000',
        'price_raw': '780000',
        'bedrooms': '2–3',
        'area': '95–140 m²',
        'image': 'https://praia.digital/img/santos-apartamento-vista-mar.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Apartamento%20vista%20mar%20Santos&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Casa pé na areia Peruíbe',
        'description': 'Casa pé na areia Peruíbe: acesso direto à praia, quintal, perfeita para temporada.',
        'city': 'peruibe',
        'type': 'casa',
        'slug': 'casa-pe-na-areia-peruibe',
        'price': 'R$ 620.000–920.000',
        'price_raw': '560000',
        'bedrooms': '2–4',
        'area': '120–200 m²',
        'image': 'https://praia.digital/img/per-sobrado.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20na%20Casa%20p%C3%A9%20na%20areia%20Peru%C3%ADbe&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Apartamento temporada Mongaguá',
        'description': 'Apartamento temporada Mongaguá: estrutura completa para locação curta, alta procura na temporada.',
        'city': 'mongagua',
        'type': 'apartamento',
        'slug': 'apartamento-temporada-mongagua',
        'price': 'R$ 260.000–420.000',
        'price_raw': '340000',
        'bedrooms': '1–2',
        'area': '50–80 m²',
        'image': 'https://praia.digital/img/mon-ap-compacto.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Apartamento%20temporada%20Mongagu%C3%A1&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Cobertura vista mar Santos',
        'description': 'Cobertura vista mar Santos: terraço panorâmico, piscina privativa, lazer completo e 3 vagas.',
        'city': 'santos',
        'type': 'cobertura',
        'slug': 'cobertura-vista-mar-santos',
        'price': 'R$ 1.050.000–1.480.000',
        'price_raw': '1250000',
        'bedrooms': '3–4',
        'area': '170–230 m²',
        'image': 'https://praia.digital/img/santos-apartamento-vista-mar.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20na%20Cobertura%20vista%20mar%20Santos&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Terreno loteamento Praia Grande',
        'description': 'Terreno loteamento Praia Grande: documento regular, topografia plana, excelente para construção.',
        'city': 'praia-grande',
        'type': 'terreno',
        'slug': 'terreno-loteamento-praia-grande',
        'price': 'R$ 180.000–320.000',
        'price_raw': '250000',
        'bedrooms': '',
        'area': '180–360 m²',
        'image': 'https://praia.digital/img/pg-studio-moderno.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Terreno%20loteamento%20Praia%20Grande&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
    {
        'title': 'Sobrado 3 quartos São Vicente',
        'description': 'Sobrado 3 quartos São Vicente: garagem coberta, quintal amplo, boa valorização.',
        'city': 'sao-vicente',
        'type': 'sobrado',
        'slug': 'sobrado-3-quartos-sao-vicente',
        'price': 'R$ 430.000–690.000',
        'price_raw': '560000',
        'bedrooms': '3',
        'area': '110–160 m²',
        'image': 'https://praia.digital/img/sv-cobertura-duplex.jpg',
        'tags': '',
        'related': '',
        'whatsapp_link': 'https://wa.me/5511954346288?text=Ol%C3%A1!%20Tenho%20interesse%20no%20Sobrado%203%20quartos%20S%C3%A3o%20Vicente&utm_source=site&utm_medium=whatsapp&utm_campaign=geral',
    },
]

merged = {r['slug']: r for r in clean}
new_count = 0
for r in new_rows:
    slug = r['slug']
    if slug not in merged:
        merged[slug] = r
        new_count += 1
    else:
        merged[slug].update(r)

with open(csv_path, 'w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for r in merged.values():
        writer.writerow(r)

print('new_count', new_count)
print('csv_rows_now', len(merged))
