KB4 = {}

KB4['ATENDIMENTO'] = {
 'familia': 'Atendimento e Relacionamento com Clientes',
 'modulos': [
  {'t':'Fundamentos do Atendimento Imobiliário','obj':'Construir a base de um atendimento que gera confiança imediata.','aulas':[
   {'t':'Os primeiros 5 minutos: como a confiança nasce','c':'O cliente decide se confia em você antes de decidir sobre o imóvel. Os 5 primeiros minutos definem: pontualidade, preparo (saber o nome do cliente e o que ele buscou), escuta real e postura consultiva.\n\nRegra prática: no primeiro contato, o cliente deve falar 70% do tempo. Faça perguntas abertas ("o que é indispensável para vocês?") e anote as palavras exatas do cliente — elas serão sua ferramenta de fechamento depois.','p':['Prepare 3 perguntas abertas de abertura','Registre as palavras exatas do cliente no CRM','Avalie-se: no último atendimento, quem falou mais?']},
   {'t':'Escuta ativa e espelhamento','c':'Escuta ativa é técnica, não dom: parafrasear ("se entendi, o quintal para o cachorro é inegociável"), validar emoções ("imagino que a mudança de cidade preocupe") e resumir antes de avançar.\n\nEspelhamento (matching): adapte ritmo e canal ao cliente — cliente objetivo recebe resposta direta; cliente analítico recebe planilha; cliente relacional recebe conversa. Errar o canal certo para a pessoa errada é a causa invisível de leads que "esfriam".','p':['Pratique parafrasear em 3 atendimentos reais','Classifique seus leads: objetivo, analítico ou relacional','Adapte o próximo contato ao estilo de cada um']},
   {'t':'Atendimento multicanal com padrão','c':'WhatsApp, ligação, e-mail e presencial têm funções diferentes: WhatsApp para agilidade e confirmações, ligação para temas sensíveis (proposta, negociação), e-mail para formalização e presencial para decisão. Documente tudo relevante por escrito — inclusive o combinado por telefone ("conforme conversamos, fica registrado...").\n\nPadrão de resposta: até 15 min no horário comercial para leads novos, até 2h para clientes em processo. Fora do horário, resposta automática inteligente com previsão de retorno.','p':['Defina seu SLA de resposta por canal','Crie o hábito do registro escrito pós-ligação','Configure resposta automática fora do horário']} ]},
  {'t':'Gestão de Conflitos e Momentos Difíceis','obj':'Conduzir situações tensas sem perder o cliente nem a venda.','aulas':[
   {'t':'O protocolo de 4 passos para qualquer reclamação','c':'1) Ouça sem interromper até o fim (a raiva precisa sair); 2) Valide o sentimento sem admitir culpa automática ("entendo sua frustração com o prazo"); 3) Apresente o que é possível fazer, com prazo; 4) Confirme a solução e acompanhe até o fim.\n\nParadoxo do atendimento: cliente que teve problema resolvido com excelência fica mais fiel que o que nunca teve problema. A crise é a oportunidade disfarçada.','p':['Memorize os 4 passos e use na próxima reclamação','Documente cada conflito e a solução aplicada','Faça follow-up 7 dias após cada problema resolvido']},
   {'t':'Comunicação difícil: atraso, reprovação e desistência','c':'Notícia ruim não melhora com o tempo — piora. Reprovou o crédito? Ligue no mesmo dia com o diagnóstico e o plano B. Atrasou o documento? Avise antes do cliente descobrir, com a nova data e o que está sendo feito.\n\nEstrutura da conversa difícil: fato (sem enrolação), impacto (reconheça), plano (2 opções quando possível) e próximo passo com data. Cliente perdoa problema; não perdoa sumiço.','p':['Escreva seu roteiro para as 3 notícias ruins mais comuns','Regra pessoal: notícia ruim no mesmo dia, sempre','Prepare sempre 2 opções antes de comunicar o problema']},
   {'t':'Inteligência emocional sob pressão','c':'Negociação imobiliária mexe com dinheiro, família e sonho — tensão é parte do jogo. Técnicas práticas: pausa antes de responder provocação (respire, conte até 5), separar a pessoa do problema ("nós dois queremos que essa venda aconteça; o ponto é o prazo") e nunca decidir no calor ("deixa eu verificar e te respondo até 18h").\n\nAutoconhecimento operacional: saiba seu gatilho (desrespeito? pressa? desorganização?) e tenha um plano para ele. O profissional que se conhece não explode no momento mais caro.','p':['Identifique seu principal gatilho emocional','Adote a pausa de 5 segundos antes de responder','Use "deixa eu verificar" como ferramenta legítima']} ]},
  {'t':'Relacionamento de Longo Prazo','obj':'Construir a base de clientes que volta e indica.','aulas':[
   {'t':'O CRM como memória do relacionamento','c':'Anote tudo: nomes dos filhos, time, motivo da compra, datas importantes, preferências. O corretor que liga no aniversário da compra e pergunta do cachorro pelo nome não é lembrado como vendedor — é lembrado como referência.\n\nSegmente a base: clientes em processo, clientes pós-venda (12 meses), base quente (podem indicar) e base fria (nutrição trimestral). Cada grupo tem cadência e conteúdo próprios.','p':['Complete os dados pessoais dos 10 clientes mais recentes','Segmente sua base nos 4 grupos','Programe as datas de aniversário de compra']},
   {'t':'Fidelização: cliente que compra de novo','c':'O cliente imobiliário volta: upgrade, imóvel para filho, investimento. O ciclo médio de recompra é de 5-8 anos — quem sumiu depois da escritura não participa da segunda venda.\n\nRégua de longo prazo: contato semestral com valor real (valorização do bairro, oportunidade alinhada ao perfil, convite). E a regra de ouro da indicação: peça no momento do elogio, com facilidade total (seu contato pronto para encaminhar).','p':['Agende contatos semestrais para a base pós-venda','Crie seu "cartão de indicação" digital (contato pronto para compartilhar)','Mapeie quais clientes têm perfil de recompra em 3-5 anos']},
   {'t':'Gestão de expectativas: o segredo da satisfação','c':'Quase toda decepção de cliente nasce de expectativa mal calibrada. Prometa o prazo realista com margem (documento em 10 dias? prometa 15 e entregue em 10), explique os riscos antes deles acontecerem e alinhe o que depende de você versus o que depende de terceiros (banco, cartório, construtora).\n\nA fórmula da satisfação é simples: expectativa < entrega. O corretor que promete pouco e entrega muito coleciona fãs; o que promete tudo e entrega o normal coleciona reclamações.','p':['Revise suas promessas-padrão: há margem nelas?','Adicione o mapa de riscos ao seu processo de venda','Prometa 15, entregue 10: teste na próxima semana']} ]},
  {'t':'Excelência Operacional do Atendimento','obj':'Padronizar a excelência para ela não depender do seu humor.','aulas':[
   {'t':'Scripts e padrões: a excelência replicável','c':'Padronize sem robotizar: scripts de primeiro atendimento, confirmação de visita, pós-visita, envio de proposta e pós-venda. O script garante o piso — nenhum cliente recebe atendimento ruim — e libera sua energia para personalizar o que importa.\n\nTeste e evolua: revise os scripts trimestralmente com base no que os clientes perguntam. O script que não muda há um ano está desatualizado com o mercado.','p':['Escreva seus 5 scripts essenciais','Revise 1 script por trimestre','Treine até o script virar conversa, não leitura']},
   {'t':'Medindo a qualidade: NPS e feedback estruturado','c':'Meça o que quer melhorar: aplique o NPS simples ("de 0 a 10, quanto indicaria meu trabalho?") ao fim de cada processo e pergunte o porquê da nota. Detratores (0-6) viram plano de correção; promotores (9-10) viram depoimento e indicação.\n\nFeche o ciclo: todo feedback gera uma ação registrada. O cliente que vê sua sugestão implementada se sente dono do processo — e defende sua marca.','p':['Implante a pergunta NPS ao fim de cada venda','Registre feedbacks e ações em planilha única','Converta 1 promotor em depoimento público por mês']},
   {'t':'Trabalho em equipe e multiplicação','c':'Quando a agenda estoura, a escolha é entre perder qualidade ou multiplicar braços. Caminho profissional: primeiro padronize seus processos (scripts, checklists, CRM), depois traga o assistente/parceiro júnior e treine nos padrões escritos.
\nDelegação que funciona: delegue tarefas com padrão definido (confirmações, agendamentos, montagem de pastas) e mantenha com você o que decide dinheiro (negociação, fechamento, relacionamento-chave).','p':['Documente seus 5 processos principais antes de contratar','Defina o que nunca será delegado','Crie o treinamento de onboarding de 1 semana']} ]} ]}

KB4['DOCUMENTACAO'] = {
 'familia': 'Documentação, Avaliação e Segurança Jurídica',
 'modulos': [
  {'t':'Documentação do Imóvel','obj':'Dominar a documentação que sustenta qualquer negociação segura.','aulas':[
   {'t':'A matrícula: a certidão de nascimento do imóvel','c':'A matrícula no Cartório de Registro de Imóveis é o documento-mestre: nela constam o histórico de proprietários, ônus (hipotecas, penhoras), ações que afetam o imóvel e averbações (construção, desmembramento). Regra absoluta: nenhuma negociação avança sem matrícula atualizada (máx. 30 dias).\n\nLeitura prática: verifique a cadeia de proprietários (faz sentido?), os ônus ativos (hipoteca precisa de carta de quitação para venda) e se a construção está averbada — imóvel sem averbação tem problemas para financiar e segurar.','p':['Solicite a matrícula atualizada de 1 imóvel e pratique a leitura','Identifique: proprietários, ônus, averbações','Crie o hábito: matrícula antes de anunciar']},
   {'t':'Certidões negativas: o raio-X dos vendedores','c':'O imóvel responde por dívidas: IPTU, condomínio e — atenção — dívidas do vendedor que podem atingir o imóvel (ações reais, penhoras). O pacote mínimo: certidões federais, estaduais, municipais, trabalhistas e de protesto de todos os vendedores (e cônjuges).\n\nCaso clássico no litoral: imóvel herança com inventário não concluído, ou vendedor empresa com ação trabalhista. A dívida pode "grudar" no imóvel. Quando houver qualquer sinal amarelo, envolva advogado antes de assinar qualquer papel.','p':['Monte o checklist de certidões por tipo de vendedor (PF, PJ, herança)','Aprenda a ler a certidão trabalhista (o que buscar)','Tenha 1 advogado imobiliário de confiança']},
   {'t':'Documentos de regularização: habite-se, averbação e área de marinha','c':'Habite-se comprova que a construção foi aprovada; sem ele, financiamento é difícil e o seguro pode negar sinistro. Averbação registra a construção na matrícula. E atenção litorânea: imóveis em terreno de marinha (faixas próximas ao mar definidas por regra federal) pagam taxa anual (foro/laudêmio) e têm regras específicas de transferência.\n\nNo litoral paulista, áreas de marinha são comuns em trechos antigos de Santos, Guarujá e Praia Grande. Não é impedimento, mas o comprador precisa saber antes — surpresa na escritura destrói negócio e reputação.','p':['Verifique se há áreas de marinha nos seus bairros de atuação','Inclua habite-se/averbação no checklist de captação','Explique foro/laudêmio em 2 frases para um colega']} ]},
  {'t':'Avaliação de Imóveis','obj':'Precificar com método e credibilidade técnica.','aulas':[
   {'t':'O método comparativo de mercado','c':'É o método padrão do corretor: comparar o imóvel com similares vendidos recentemente, ajustando pelas diferenças (andar, vista, conservação, garagem). Fontes: fechamentos reais da sua rede, valores de anúncio corrigidos pelo deságio típico (10-20% no litoral) e dados de cartório.\n\nQualidade da amostra: mínimo 3 comparáveis, ideal 5-7, do mesmo bairro e padrão, vendidos nos últimos 6 meses. Comparável de 2 anos atrás em mercado aquecido vale pouco.','p':['Monte sua base de comparáveis por bairro','Corrija 3 anúncios pelo deságio típico local','Produza 1 avaliação completa pelo método comparativo']},
   {'t':'Fatores de valor: o que pesa mais no litoral','c':'No litoral, os multiplicadores de valor têm hierarquia própria: distância do mar (frente-mar pode valer 40-60% mais que 3ª quadra), vista permanente (verifique o que pode ser construído na frente!), estado de conservação frente à maresia, sol da manhã vs. sol da tarde, e infraestrutura do condomínio.\n\nDocumente cada ajuste: a avaliação defensável é a que mostra os fatores. "Vale R$ 800 mil porque sim" não convence proprietário nem comprador; "vale porque o comparável X vendeu por Y ajustado por Z" convence.','p':['Monte sua tabela de fatores com pesos típicos locais','Verifique plano diretor/gabarito dos terrenos em frente a 1 imóvel com vista','Apresente 1 avaliação com fatores documentados']},
   {'t':'Quando chamar o PTAM: a avaliação formal','c':'O PTAM (Parecer Técnico de Avaliação Mercadológica) é a avaliação formal emitida por corretor com especialização, seguindo norma ABNT — exigido em disputas judiciais, partilhas e operações que precisam de respaldo documental. É um serviço pago à parte da corretagem e uma fonte extra de renda para o corretor especializado.\n\nDiferença prática: a avaliação comparativa informal orienta a negociação do dia a dia; o PTAM tem valor técnico formal. Saber a diferença — e ter um avaliador parceiro — resolve o cliente que precisa do documento.','p':['Entenda quando o PTAM é exigido (3 situações)','Tenha 1 avaliador PTAM parceiro','Considere a especialização em avaliações como fonte de renda']} ]},
  {'t':'Contratos e Formalização','obj':'Garantir que o combinado vire documento válido.','aulas':[
   {'t':'Do sinal à escritura: a sequência correta','c':'Sequência segura: proposta por escrito → contrato de compra e venda (ou promessa, conforme o caso) com sinal → due diligence completa → escritura pública → registro na matrícula (só o registro transfere a propriedade). Pular etapas é o atalho que vira processo.\n\nPontos críticos do contrato: descrição exata do imóvel e da matrícula, condições de pagamento, prazos, multa por desistência (arras — em geral 10-25% do sinal), e condição suspensiva de financiamento quando houver (se o banco não aprovar, devolve o sinal).','p':['Revise seu modelo de contrato de sinal','Inclua sempre a cláusula de condição de financiamento','Explique a diferença escritura x registro em 2 frases']},
   {'t':'Golpes imobiliários: os padrões que se repetem no litoral','c':'Os 4 golpes mais comuns: vendedor falso com documentos adulterados (sempre confira identidade presencialmente ou por reconhecimento), imóvel com ônus ocultado (matrícula velha "para facilitar"), loteamento irregular em área de preservação e o falso corretor que cobra "taxa de reserva" e some.\n\nBlindagem: matrícula sempre nova e pedida por você (não aceite PDF enviado), pagamentos sempre rastreáveis e nunca em dinheiro, e desconfiança saudável de urgência artificial ("tem outro comprador com dinheiro na mão hoje").','p':['Adote a regra: matrícula só pedida por você, sempre recente','Nunca intermedie pagamento em dinheiro','Documente os 4 padrões de golpe e compartilhe com clientes']},
   {'t':'Escritura, registro e custos: o fechamento sem sustos','c':'Custos de fechamento que o comprador precisa conhecer no primeiro dia: ITBI (2-3% conforme o município), escritura pública e registro (tabelados por valor, em geral ~1% combinados), e certidões. Em financiamento, somam-se avaliação e tarifas bancárias.\n\nO registro é o que transfere a propriedade — a escritura sozinha não basta. Acompanhe o cliente até a averbação final: o processo termina no cartório de registro, não no tabelionato.','p':['Monte a tabela de custos de fechamento das suas cidades','Explique a tríade proposta→escritura→registro em 3 frases','Acompanhe 1 processo até a averbação final']} ]},
  {'t':'Visita Técnica e Vistoria Profissional','obj':'Avaliar o estado real do imóvel com olhar técnico.','aulas':[
   {'t':'A vistoria estruturada: os 20 pontos do checklist','c':'Vistoria profissional cobre: estrutura (rachaduras em vigas e pilares x fissuras de revestimento), hidráulica (pressão, sinais de vazamento, esgoto), elétrica (quadro, tomadas, aquecimento), cobertura/telhado (umidade no forro) e as especificidades do litoral: corrosão em esquadrias e ferragens, impermeabilização de fachada e áreas de condomínio expostas ao sal.\n\nFotografe tudo com referência de escala e monte o laudo simples: ponto, condição, foto, recomendação. O laudo vira peça de negociação — problemas documentados justificam desconto.','p':['Monte seu checklist de 20 pontos','Vistorie 1 imóvel aplicando o checklist completo','Produza 1 laudo fotográfico simples']},
   {'t':'Maresia e umidade: os inimigos invisíveis do litoral','c':'A maresia (aerossol de sal) corrói metal, esquadrias e instalações em ritmo acelerado — imóvel a 100m do mar exige manutenção preventiva que o mesmo imóvel a 1 km não precisa. Na vistoria: verifique esquadrias (alumínio anodizado ou pintura eletrostática resistem mais), ferragens de portas, aparelhos de ar-condicionado e a pintura da fachada.\n\nUmidade: distinga umidade de condensação (comum em imóvel fechado na baixa temporada, resolve com ventilação) de infiltração estrutural (manchas que crescem, tinta estufada — resolve com obra). Confundir as duas compromete a avaliação.','p':['Aprenda os 3 sinais de infiltração estrutural','Verifique esquadrias e ferragens em toda vistoria litorânea','Inclua "custo de maresia" na análise de imóveis frente-mar']},
   {'t':'Apresentação técnica: transformando o laudo em argumento','c':'O laudo de vistoria serve a dois senhores: ao vendedor (transparência que acelera a venda — imóvel com laudo limpo vende mais rápido) e ao comprador (segurança para decidir). Apresente com estrutura: pontos fortes primeiro, pendências com custo estimado de correção, e comparativo com o padrão do bairro.\n\nRegra de credibilidade: nunca esconda problema documentável. O corretor que aponta a infiltração antes do cliente descobrir ganha a confiança; o que é pego escondendo perde a venda e a reputação.','p':['Crie seu modelo de apresentação de laudo','Estime custos de correção dos 5 problemas mais comuns','Adote a regra: problema documentável sempre apresentado']} ]} ]}
