# Base de conhecimento real por familia de cursos - Praia Digital Academy
KB = {}
KB['CAPTACAO'] = {
 'familia': 'Captação de Imóveis',
 'modulos': [
  {'t':'Fundamentos da Captação Profissional','obj':'Entender o papel estratégico da captação e montar a base de uma carteira sólida no litoral paulista.','aulas':[
   {'t':'O mercado imobiliário do litoral paulista: dados e dinâmica','c':'O litoral de São Paulo concentra dois mercados distintos: o de moradia permanente (Baixada Santista, com Santos e Guarujá à frente) e o de segunda residência/temporada (forte em Ubatuba, Ilhabela, Caraguatatuba e São Sebastião). Cerca de 60% dos imóveis à venda em cidades como Ilhabela pertencem a proprietários não residentes — o que muda completamente a abordagem de captação: o contato inicial é quase sempre remoto, a confiança é construída por consistência, e a documentação costuma ter pendências (inventários, usufrutos, averbações).\n\nO corretor que entende essa dinâmica para de disputar os mesmos imóveis anunciados nos portais e passa a criar carteira própria. A regra prática do mercado: quem capta bem escolhe com quem trabalha; quem não capta aceita qualquer imóvel e qualquer condição.','p':['Mapeie sua cidade: bairros de moradia fixa x bairros de temporada','Liste 10 ruas/condomínios prioritários para monitorar','Identifique em cada um: perfil do proprietário (residente ou não), ticket médio e giro estimado']},
   {'t':'Captação ativa x captação passiva: onde investir seu tempo','c':'Captação passiva é esperar o proprietário chegar (anúncios, placas, indicação espontânea). Captação ativa é ir ao encontro: porta a porta em condomínios-alvo, contato com síndicos, zeladores e administradoras, monitoramento de anúncios "vende-se pelo proprietário" e redes de relacionamento (advogados de família, contadores, gerentes de banco).\n\nNo litoral, a captação ativa rende mais porque muitos proprietários moram na capital e não têm vínculo com imobiliárias locais. Um roteiro profissional de primeiro contato — apresentação objetiva, proposta de avaliação gratuita e materiais de credibilidade — converte entre 8% e 15% dos contatos frios bem escolhidos em avaliações agendadas.','p':['Defina meta semanal: 20 contatos ativos novos','Monte sua apresentação de 30 segundos (quem você é, resultado que entrega, prova)','Registre todo contato no CRM com data do próximo follow-up']},
   {'t':'Avaliação inicial do imóvel: o que observar antes de precificar','c':'Antes de falar em preço, o captador profissional levanta: localização micro (quadra, lado da rua, vista), estado de conservação real (umidade e corrosão por maresia são críticos no litoral), documentação (matrícula atualizada, IPTU, débitos de condomínio) e comparáveis reais de venda — não de anúncio.\n\nErro clássico: usar valor de anúncio de portais como referência. Anúncios no litoral ficam em média 10% a 20% acima do valor de fechamento. Trabalhe com fechamentos reais, percepção de corretores ativos e, quando possível, dados de cartório (CRI) da cidade.','p':['Crie ficha de avaliação padrão (localização, conservação, documentação, comparáveis)','Separe valor de anúncio de valor de mercado na conversa com o proprietário','Fotografe pontos críticos: fachada, infiltrações, elétrica, esquadrias (maresia)']} ]},
  {'t':'Prospecção e Abordagem','obj':'Construir uma máquina de prospecção com roteiros testados e canais mensuráveis.','aulas':[
   {'t':'Roteiros de primeiro contato que funcionam','c':'O primeiro contato define tudo. Estrutura validada: (1) contexto — por que você está ligando para aquele imóvel específico; (2) credibilidade — um resultado concreto e local ("vendi duas unidades neste condomínio este ano"); (3) pedido pequeno — não peça a captação, peça uma avaliação gratuita de 20 minutos.\n\nEvite: falar de comissão no primeiro contato, prometer valores sem ver o imóvel, e enviar textão no WhatsApp. Mensagem fria ideal tem até 4 linhas, um gancho local e um pedido claro com duas opções de horário.','p':['Escreva seus 3 roteiros: ligação, WhatsApp e presencial','Teste A/B por 2 semanas e meça taxa de resposta','Siga a régua: contato 1 (abordagem), 2 (48h, valor agregado), 3 (7 dias, case local)']},
   {'t':'Canais de prospecção no litoral: onde estão os proprietários','c':'Canais com melhor custo-benefício no litoral: administradoras de condomínio (concentram dezenas de proprietários), síndicos profissionais, grupos de Facebook de bairros, anúncios de aluguel de temporada encerrados (proprietário cansado de gerir = potencial vendedor), e parcerias com construtoras pequenas para estoque de repasse.\n\nCada canal precisa de métrica própria: contatos feitos, respostas, avaliações agendadas, captações fechadas. Sem isso, você não sabe onde dobrar o esforço.','p':['Escolha 3 canais prioritários para os próximos 90 dias','Defina meta semanal por canal e planilhe resultados','Faça parceria formal com 1 administradora de condomínios']},
   {'t':'Follow-up de captação: 80% do resultado está na persistência','c':'A maioria das captações acontece entre o 4º e o 8º contato — e a maioria dos corretores desiste no 2º. Proprietário de imóvel no litoral raramente decide rápido: o imóvel é patrimônio afetivo ou investimento parado.\n\nMonte cadências de 90 dias: contato a cada 10-15 dias, sempre com valor novo (dado de mercado do bairro, notícia local que afeta valor, comparável vendido). Nunca "só passando para saber se decidiu" — cada toque precisa dar um motivo para o proprietário lembrar que você é o profissional do assunto.','p':['Programe cadência de 90 dias no CRM para cada prospect quente','Prepare 6 "motivos de contato" prontos (dados, cases, sazonalidade)','Meça: taxa de conversão por número de toques']} ]},
  {'t':'Contrato de Captação e Exclusividade','obj':'Transformar avaliações em contratos assinados, com exclusividade quando fizer sentido.','aulas':[
   {'t':'Anatomia do contrato de captação','c':'O contrato de mediação (autorização de venda) deve conter: identificação completa das partes, descrição e matrícula do imóvel, valor e condições de venda autorizadas, prazo de vigência, percentual de comissão (padrão de mercado: 5% a 6% para venda urbana; no litoral, imóveis de alto valor podem fechar em 4% a 5%), e obrigações do corretor (plano de divulgação, relatórios).\n\nPonto jurídico essencial: mesmo sem exclusividade, o corretor que comprova ter aproximado o comprador tem direito à comissão (art. 725 do Código Civil). Mas provar é difícil — por isso registre visitas com assinatura e data.','p':['Revise seu modelo de contrato com um advogado uma vez por ano','Inclua cláusula de relatório quinzenal de divulgação','Sempre registre visitas por escrito (ficha assinada ou e-mail de confirmação)']},
   {'t':'Vendendo a exclusividade sem parecer ganancioso','c':'Exclusividade não se pede — se justifica. O argumento correto é econômico: com exclusividade, você investe dinheiro real no imóvel (fotos profissionais, anúncios patrocinados, tour virtual) e coordena a estratégia de preço sem interferência de anúncios concorrentes com valores conflitantes.\n\nApresente um plano escrito de 30-60-90 dias: o que será feito, quando e com qual investimento. Comprometa-se com relatórios quinzenais. Dê prazo de saída: contratos de 3 a 6 meses com possibilidade de rescisão mediante aviso convertem muito mais que contratos abertos.','p':['Monte sua apresentação de exclusividade em 1 página (plano 30-60-90)','Defina seu pacote mínimo de investimento por imóvel exclusivo','Treine a resposta à objeção "outra imobiliária não pede exclusividade"']},
   {'t':'Precificação orientada por dados: o momento que define a venda','c':'Imóvel com preço errado queima no mercado: os primeiros 30 dias concentram a maior parte do interesse. A técnica é apresentar três faixas com evidência: valor de liquidez rápida (vende em até 60 dias), valor de mercado (90-180 dias) e valor aspiracional (sem previsão). Deixe o proprietário escolher — mas com os números na mesa.\n\nNo litoral, inclua na análise a sazonalidade: anunciar em outubro-novembro captura a demanda de quem quer o imóvel pronto para o verão; o mesmo imóvel em abril tem menos tráfego.','p':['Monte relatório de precificação padrão com 3 faixas e justificativas','Use sempre 3+ comparáveis reais de fechamento','Reavalie o preço a cada 45 dias sem visitas qualificadas']} ]},
  {'t':'Carteira, Gestão e Escala','obj':'Gerir a carteira como ativo: rotinas, métricas e qualidade acima de quantidade.','aulas':[
   {'t':'Curva ABC da carteira: nem todo imóvel merece seu tempo','c':'Classifique cada captação: A (preço certo, documentação ok, proprietário motivado — recebe 60% do seu esforço), B (bom imóvel, preço 10% acima — trabalho de re-educação do proprietário), C (preço fora, urgência baixa — manter no radar, sem investimento).\n\nCarteira saudável no litoral: 15 a 25 imóveis ativos, com pelo menos 40% na faixa A. Mais que isso, você vira repositório de anúncios; menos, fica sem produto para oferecer.','p':['Classifique sua carteira atual em A/B/C hoje','Defina ação padrão por classe (A: divulgação ativa; B: reunião de preço; C: contato trimestral)','Desfaça parceria formal com imóveis C sem perspectiva — com elegância']},
   {'t':'Relatório ao proprietário: a ferramenta que evita perda da captação','c':'O maior motivo de perda de captação é o silêncio do corretor. Um relatório quinzenal simples (visitas realizadas, feedback dos interessados, visualizações dos anúncios, movimento do mercado no bairro) transforma a relação: o proprietário vê trabalho e confia na estratégia — inclusive para reduzir preço quando necessário.\n\nModelo eficaz: meia página, 3 números, 1 recomendação. Sem relatório, qualquer conversa de redução de preço parece desculpa; com relatório, é conclusão lógica.','p':['Crie seu modelo de relatório quinzenal (template único)','Agende envio automático a cada 15 dias por captação ativa','Use o feedback dos visitantes como evidência de preço']},
   {'t':'Métricas do captador profissional','c':'Acompanhe mensalmente: contatos de prospecção, avaliações realizadas, taxa de conversão avaliação→contrato (meta: 40%+), percentual de exclusividades, tempo médio de venda por faixa de preço e taxa de perda de captação.\n\nBenchmark prático no litoral: corretor maduro converte 1 captação a cada 8-12 avaliações em mercado aquecido e 1 a cada 15-20 em baixa temporada. Se sua taxa está muito abaixo, o problema é abordagem; se converte mas não vende, o problema é precificação.','p':['Monte painel mensal com as 6 métricas acima','Identifique seu gargalo atual: volume, conversão ou preço','Defina 1 melhoria de processo por mês']} ]} ]}

KB['VENDAS'] = {
 'familia': 'Vendas e Negociação Imobiliária',
 'modulos': [
  {'t':'Fundamentos da Venda Consultiva','obj':'Migrar do modelo de "empurrar imóvel" para a venda consultiva baseada em diagnóstico.','aulas':[
   {'t':'Como o cliente de imóvel no litoral decide','c':'O comprador de imóvel no litoral combina razão e emoção em doses que mudam conforme o perfil: o investidor decide por planilha (retorno, liquidez, custo de oportunidade); a família de segunda residência decide por imaginário (verões, filhos, status) validado por números; o morador definitivo decide por rotina (trabalho, escola, serviços).\n\nA venda consultiva começa identificando o perfil nos primeiros 10 minutos de conversa — com perguntas, não com apresentação de imóveis. Quem apresenta imóvel antes de diagnosticar vende para a planilha errada.','p':['Liste 5 perguntas de diagnóstico que separam investidor de usuário final','Identifique o perfil dos seus 5 leads ativos agora','Adapte o discurso de 1 imóvel para cada um dos 3 perfis']},
   {'t':'SPIN Selling aplicado a imóveis','c':'O método SPIN estrutura a conversa em quatro camadas: Situação (como usa imóvel hoje?), Problema (o que incomoda? custo, distância, manutenção?), Implicação (quanto custa não resolver? temporada perdida, patrimônio parado) e Necessidade de solução (o que mudaria com o imóvel certo?).\n\nExemplo real: em vez de "quer conhecer um apartamento no Guarujá?", a sequência consultiva leva o próprio cliente a concluir que manter o dinheiro parado rende menos que um imóvel com retorno de temporada de 5% a 8% ao ano em bairros valorizados.','p':['Escreva 2 perguntas de cada tipo SPIN para seu nicho','Role-play: conduza uma conversa completa sem apresentar imóvel nos primeiros 15 minutos','Registre as objeções que surgirem por tipo de pergunta']},
   {'t':'Apresentação de valor: do preço para o custo-benefício','c':'Cliente nunca acha o preço bom — acha o preço justo ou injusto para o valor percebido. Construa valor antes de falar de preço: escassez real (poucas unidades com aquela vista), custo de reconstruir (preço do m² novo no bairro), e custo de não decidir (mercado do litoral historicamente se valoriza nos ciclos de verão).\n\nTécnica da ancoragem: apresente primeiro o imóvel de maior valor da seleção. O segundo parecerá mais acessível — sem você ter dito nada sobre desconto.','p':['Para cada imóvel ativo, escreva 3 argumentos de valor não relacionados a preço','Ordene sua seleção do mais caro ao mais barato nas apresentações','Cronometre: fale de preço só depois de 3 pontos de valor']} ]},
  {'t':'Condução, Visita e Demonstração','obj':'Transformar visitas em decisões com preparação e roteiro.','aulas':[
   {'t':'Preparação da visita: o jogo se ganha antes','c':'Visita profissional começa na véspera: confirme horário e endereço, revise a ficha do lead (perfil, orçamento, objeções anteriores), prepare a ordem dos ambientes (terminar sempre no ponto mais forte do imóvel — a varanda com vista, nunca na área de serviço) e leve material de apoio: comparáveis, simulação de financiamento e estimativa de retorno se for investidor.\n\nNo litoral, detalhes matam visitas: chegue antes e verifique cheiros (umidade), iluminação e barulho da rua no horário da visita. Se houver ponto fraco evidente, prepare a resposta antes de ser perguntado.','p':['Crie checklist de pré-visita (12 itens)','Defina o roteiro de ambientes dos seus 3 imóveis principais','Prepare a resposta para o ponto fraco de cada um']},
   {'t':'Técnicas de condução durante a visita','c':'Durante a visita, fale menos que o cliente. Use a técnica das perguntas de confirmação: "essa cozinha atenderia os almoços de família que você mencionou?" — cada "sim" é um micro-fechamento. Observe o tempo que o cliente passa em cada ambiente: onde ele demora é onde está a decisão.\n\nSinais de compra a monitorar: perguntas sobre documentação, prazo de entrega, condomínio, possibilidade de reforma e "o que preciso fazer para reservar?". Ao primeiro sinal, pare de apresentar e comece a conduzir o próximo passo.','p':['Liste 5 perguntas de confirmação para seu imóvel principal','Treine identificar 4 sinais de compra','Defina sua frase de transição visita→proposta']},
   {'t':'O fechamento da visita: próximo passo claro','c':'Visita sem próximo passo agendado é visita perdida. Antes de sair do imóvel, defina: ou o cliente faz proposta, ou agenda segunda visita, ou recebe simulação de financiamento até determinada hora no dia seguinte — com data e hora marcadas para a conversa de retorno.\n\nRegra de ouro: quem controla a agenda controla a venda. "Eu te mando e você vê com calma" entrega o controle; "amanhã às 10h te ligo com a simulação e conversamos" mantém o processo vivo.','p':['Padronize os 3 próximos passos possíveis pós-visita','Nunca encerre contato sem data/hora do seguinte','Registre no CRM o compromisso assumido pelo cliente']} ]},
  {'t':'Objeções e Negociação','obj':'Tratar objeções como pedidos de informação e conduzir negociações ganha-ganha.','aulas':[
   {'t':'As 6 objeções que dominam o mercado do litoral','c':'1) "Está caro" — quase sempre é valor não construído, não preço; 2) "Vou pensar" — falta informação ou há objeção oculta; 3) "Preciso falar com meu cônjuge" — você apresentou para o decisor errado ou não envolveu ambos; 4) "Vou esperar baixar" — mostre o histórico de valorização do bairro e o custo de oportunidade; 5) "Não tenho entrada" — apresente alternativas reais (FGTS, financiamento direto com construtora, imóvel de menor valor); 6) "O condomínio é alto" — compare com o custo de manter casa de praia própria (IPTU, segurança, manutenção).\n\nPara cada uma, a técnica base é a mesma: valide ("entendo, faz sentido"), isole ("se resolvermos isso, fechamos?") e responda com evidência.','p':['Escreva sua resposta para cada uma das 6 objeções','Treine validar-isolar-responder em role-play','Registre no CRM qual objeção mais aparece nos seus leads']},
   {'t':'Negociação de preço: protegendo o valor sem perder o cliente','c':'Nunca aceite nem recuse a primeira proposta imediatamente. A técnica do recuo gradual: cada concessão sua deve ser menor que a anterior e acompanhada de uma contrapartida (prazo, entrada maior, inclusão de mobília). Se o cliente pede 10% de desconto, conceda no máximo em etapas: 3%, depois 2%, depois 1% — a curva decrescente sinaliza o limite.\n\nE lembre: quem fala o primeiro número perde a ancoragem, mas quem ancora bem define o campo da negociação. Em vendas para investidores, ancore no retorno; para famílias, ancore no estilo de vida.','p':['Defina seus limites de concessão por imóvel antes de qualquer proposta','Monte tabela de contrapartidas possíveis (prazo, entrada, mobília, documentação)','Pratique a frase: "posso trabalhar esse valor se ajustarmos X"']},
   {'t':'Fechamento: as 5 técnicas essenciais','c':'1) Fechamento direto — quando os sinais são claros, peça: "vamos reservar?"; 2) Fechamento alternativo — "prefere assinar sexta ou segunda?"; 3) Fechamento por resumo — recapitule os 3 pontos decisivos e conclua; 4) Fechamento de urgência legítima — apenas com urgência real (outra proposta em análise, fim de condição); urgência fabricada destrói confiança; 5) Fechamento por eliminação — remova a última objeção e confirme.\n\nDepois do "sim", silêncio e ação: encaminhe documentação imediatamente. O período entre o aceite e a assinatura é onde morrem 20% das vendas.','p':['Identifique qual técnica combina com seu estilo e treine-a até naturalizar','Cronometre: do aceite verbal ao envio de documentos, máximo 2 horas','Monitore sua taxa de perda pós-aceite']} ]} ]}
