KB2 = {}

KB2['VENDAS_M'] = [
  {'t':'Funil de Vendas Imobiliário','obj':'Organizar o pipeline para prever receita e não perder oportunidades.','aulas':[
   {'t':'As 5 etapas do funil imobiliário','c':'Lead novo → Qualificado (orçamento e perfil confirmados) → Visita agendada → Proposta → Fechamento. Cada etapa tem taxa de conversão típica: lead→qualificado 40-60%, qualificado→visita 30-50%, visita→proposta 15-25%, proposta→fechamento 50-70%.\n\nCom esses números você descobre quantos leads precisa por mês para bater a meta: para 2 vendas/mês, são necessárias ~4 propostas, ~20 visitas e ~50 leads qualificados. Sem funil, o corretor vive de sorte; com funil, vive de processo.','p':['Desenhe seu funil atual com as 5 etapas','Preencha com seus números dos últimos 90 dias','Identifique a etapa com maior vazamento e ataque-a']},
   {'t':'Qualificação de leads: BANT adaptado ao imobiliário','c':'Qualifique com 4 perguntas: Budget (faixa de investimento real, origem dos recursos — financiamento, FGTS, à vista), Autoridade (quem decide? casal decide junto no litoral), Necessidade (uso: moradia, temporada, investimento) e Tempo (quando pretende decidir).\n\nLead desqualificado consome 70% do tempo do corretor mal organizado. Regra prática: lead sem orçamento definido e sem prazo vai para fluxo de nutrição, não para visita.','p':['Aplique as 4 perguntas nos seus 10 leads ativos','Separe: visita esta semana / nutrição / descarte','Configure tags de qualificação no CRM']},
   {'t':'Velocidade de resposta: a métrica que decide vendas','c':'Estudos de inside sales mostram que responder o lead em até 5 minutos multiplica por até 8 a chance de qualificação comparado a 30 minutos. No WhatsApp do litoral, o lead que pergunta sobre um imóvel às 21h está olhando 3 concorrentes ao mesmo tempo.\n\nEstruture: resposta automática inteligente fora do horário, plantão de resposta nos horários de pico (12h-14h e 19h-22h) e primeira resposta sempre com pergunta de qualificação, nunca só "oi, tudo bem?".','p':['Meça seu tempo médio de resposta atual','Configure resposta automática com 1 pergunta de qualificação','Defina plantão de resposta nos horários de pico']} ]},
  {'t':'Pós-venda e Receita Recorrente','obj':'Transformar clientes em fonte de indicações e novas vendas.','aulas':[
   {'t':'O roteiro de pós-venda de 12 meses','c':'7 dias: check de adaptação e documentação. 30 dias: confirmação de registros e mudança. 90 dias: indicações de serviços locais (zelador, limpeza, gestão de temporada). 180 dias: atualização de valor de mercado do imóvel — o cliente adora saber que valorizou. 365 dias: aniversário de compra + pedido de indicação.\n\nCada toque é sem venda: o objetivo é presença. A venda seguinte vem naturalmente — upgrade, segunda unidade ou indicação.','p':['Cadastre todos os clientes dos últimos 24 meses na régua','Envie 3 contatos de pós-venda esta semana','Peça indicação apenas nos toques 180 e 365']},
   {'t':'Programa de indicações que funciona','c':'Indicação não se compra com comissão ao cliente (isso é estranho no imobiliário) — se cultiva com experiência memorável e pedido no momento certo: logo após o elogio espontâneo.\n\nRoteiro natural: "Fico feliz que tenha gostado do processo. Se surgir alguém próximo pensando em imóvel no litoral, ficarei honrado em cuidar com o mesmo capricho." Sem pressão, sem folheto. E quando a indicação chegar, dê tratamento VIP e avise o indicador do andamento (sem violar sigilo).','p':['Identifique 3 clientes que elogiaram seu trabalho','Faça o pedido de indicação com o roteiro natural','Crie o ritual: indicado vira VIP e indicador é atualizado']} ]}]

KB2['FINANCIAMENTO'] = {
 'familia': 'Financiamento Imobiliário',
 'modulos': [
  {'t':'Sistemas e Regras do Financiamento','obj':'Dominar as regras do jogo: SFH, SFI, amortização e os programas habitacionais.','aulas':[
   {'t':'SFH, SFI e Minha Casa Minha Vida: o mapa completo','c':'O SFH (Sistema Financeiro da Habitação) usa recursos da poupança e do FGTS, com taxas mais baixas e teto de valor de imóvel (R$ 1,5 milhão nas grandes regiões metropolitanas). Acima disso, o crédito é SFI — recursos livres dos bancos, taxas maiores, sem subsídio.\n\nO Minha Casa Minha Vida (faixas por renda familiar) oferece subsídio e taxas reduzidas, mas tem limites de valor do imóvel e regras de enquadramento — verifique os valores vigentes, que são atualizados periodicamente. No litoral, atenção: imóveis de temporada e casas em condomínio de alto padrão raramente se enquadram; já apartamentos compactos em Praia Grande, Mongaguá e Peruíbe frequentemente sim.','p':['Monte uma tabela de enquadramento: SFH x SFI x MCMV com tetos atuais','Verifique o teto do MCMV vigente nas cidades onde você atua','Identifique 3 imóveis da sua carteira enquadráveis no MCMV']},
   {'t':'Tabela Price x SAC na prática (com números)','c':'Na Price, a parcela é fixa; no SAC, a amortização é fixa e a parcela decresce. Exemplo: R$ 300.000 a 10% a.a. (≈0,797% a.m.) por 360 meses — Price: parcela fixa de ~R$ 2.633; SAC: primeira parcela ~R$ 3.225, última ~R$ 840. Juros totais: Price ≈ R$ 648 mil; SAC ≈ R$ 542 mil.\n\nRegra prática para o cliente: se a renda comporta a parcela inicial do SAC (os bancos exigem comprometimento de até 30% da renda), o SAC economiza juros; se o orçamento é apertado no início, a Price cabe no bolso. Explique isso com a simulação na mão e você vira consultor, não vendedor.','p':['Refaça a simulação acima na calculadora ou planilha','Prepare 1 simulação Price x SAC para cada faixa de preço da sua carteira','Treine explicar a diferença em 60 segundos']},
   {'t':'FGTS, subsídio e composição de renda','c':'O FGTS pode ser usado para entrada, amortização ou pagamento de parcelas, desde que o comprador tenha 3 anos de registro, não tenha imóvel na mesma cidade e não tenha financiamento ativo no SFH. A composição de renda permite somar renda de cônjuge, e alguns bancos aceitam parentes.\n\nDetalhe que reprova: renda informal sem comprovação. Autônomos devem organizar extratos, declaração de IR ou Decore feita por contador antes de simular. Orientar o cliente nessa preparação vale mais que qualquer desconto.','p':['Monte checklist de elegibilidade FGTS (3 regras)','Liste os documentos de renda para CLT, autônomo e aposentado','Tenha contato de 1 contador parceiro para Decore']} ]},
  {'t':'Aprovação de Crédito e Documentação','obj':'Conduzir o cliente até a aprovação sem surpresas.','aulas':[
   {'t':'Análise de crédito: o que o banco realmente olha','c':'O banco avalia score de crédito, comprometimento de renda (máx. 30%), estabilidade profissional, vínculo com a região e o próprio imóvel (avaliação do engenheiro). Restrições em órgãos de proteção quase sempre reprovam — verifique antes de simular.\n\nNo litoral, atenção redobrada com imóveis em áreas de preservação, sem habite-se ou com documentação irregular de terreno: o banco reprova o imóvel, não o cliente. Verifique a documentação do imóvel antes de prometer aprovação.','p':['Inclua "situação de crédito" na qualificação do lead','Exija matrícula atualizada antes de iniciar processo','Mapeie 2 engenheiros avaliadores que atendem os bancos locais']},
   {'t':'Documentação completa: o checklist que evita 90% das reprovações','c':'Do comprador: RG/CNH, CPF, comprovante de estado civil, comprovantes de renda (3 últimos holerites ou Decore), IR, comprovante de residência. Do imóvel: matrícula atualizada, certidões negativas dos vendedores, IPTU, habite-se e convenção de condomínio se houver.\n\nFluxo profissional: pasta digital padronizada por cliente, documentos nomeados, checklist compartilhado. O corretor que entrega a pasta completa ao banco reduz o tempo de análise de semanas para dias — e vira referência para os gerentes, que passam a indicar clientes.','p':['Crie a pasta digital padrão com o checklist','Cronometre seu tempo médio atual de montagem de processo','Apresente-se a 2 gerentes de banco com seu processo organizado']},
   {'t':'Recusa de crédito: o plano B profissional','c':'Reprovou? Diagnostique o motivo real (score, renda, imóvel) antes de tentar outro banco — tentativas em sequência sem correção derrubam o score. Alternativas reais: financiamento direto com a construtora (comum em lançamentos do litoral), consórcio contemplado, aumento de entrada com prazo, ou reposicionar o cliente para imóvel de menor valor.\n\nComunique a recusa com plano anexo: "o banco X reprovou por Y; o caminho é Z em N meses". Cliente bem tratado na recusa volta — e indica.','p':['Crie a árvore de alternativas pós-recusa (4 caminhos)','Tenha 1 contato de construtora com financiamento direto','Documente o motivo de cada recusa para aprender o padrão']} ]},
  {'t':'Simulações e Atendimento Consultivo','obj':'Usar simulações como ferramenta de venda consultiva.','aulas':[
   {'t':'Montando a simulação completa para o cliente','c':'Uma simulação profissional mostra: valor do imóvel, entrada mínima (20% padrão SFH), valor financiado, parcela Price e SAC, custo efetivo total (CET, que inclui seguros MIP/DFI e taxa de abertura) e comprometimento de renda.\n\nApresente sempre dois cenários (banco A x banco B, ou Price x SAC) — a comparação dá ao cliente sensação de controle e reduz o "vou pensar". Ferramentas: simuladores oficiais da Caixa e dos bancos privados, ou planilha própria validada.','p':['Monte seu modelo de simulação de 2 cenários','Inclua sempre o CET, nunca só a taxa nominal','Teste a simulação com um colega antes de usar com cliente']},
   {'t':'Custos além da parcela: o que o cliente precisa saber','c':'Além das parcelas: ITBI (2% a 3% do valor, conforme a cidade do litoral), registro em cartório (~1%), avaliação do imóvel, seguros MIP/DFI embutidos na parcela e taxa de relacionamento bancário. Um financiamento de R$ 300 mil carrega R$ 10 a 15 mil de custas iniciais.\n\nO corretor que surpreende o cliente no cartório perde a venda; o que apresenta a planilha completa de custos no primeiro encontro ganha autoridade. Inclua essa planilha em toda proposta.','p':['Monte a planilha de custos totais (ITBI, registro, taxas, seguros)','Verifique a alíquota de ITBI das suas cidades de atuação','Entregue a planilha em toda proposta']} ]},
  {'t':'Estratégias Avançadas e Casos do Litoral','obj':'Resolver casos complexos e ampliar o leque de soluções.','aulas':[
   {'t':'Financiamento para aposentados e compradores 50+','c':'A soma da idade do comprador com o prazo do financiamento não pode ultrapassar o limite do banco (em geral 80 anos e 6 meses). Isso reduz o prazo e aumenta a parcela — mas há estratégias: prazo menor com SAC, entrada maior, inclusão de co-participante mais jovem e seguros com coberturas ajustadas.\n\nO litoral paulista tem demanda fortíssima de aposentados (migração para Praia Grande, Mongaguá, Itanhaém). Quem domina esse nicho domina um dos mercados que mais crescem na região.','p':['Simule 1 caso 60+ com prazo limitado','Liste 3 imóveis da carteira ideais para esse perfil (acessibilidade, serviços próximos)','Crie um roteiro de atendimento específico para aposentados']},
   {'t':'Imóvel na planta x pronto: fluxos de pagamento diferentes','c':'Na planta, o cliente paga entrada + parcelas à construtora durante a obra (corrigidas pelo INCC) e só financia o saldo na entrega das chaves. Pronto: financia tudo de uma vez. O erro é o cliente não prever a correção do INCC na fase de obra — em ciclos de construção cara, o saldo devedor cresce 6% a 10% ao ano.\n\nOriente com simulação de evolução do saldo devedor durante a obra. Cliente preparado não desiste no meio — e desistência na planta devolve imóvel ao mercado com deságio, oportunidade para investidores da sua rede.','p':['Monte simulador de evolução de saldo com INCC','Explique o fluxo na planta em 3 etapas para um colega','Tenha 1 lançamento mapeado com fluxo detalhado da construtora']},
   {'t':'Case completo: da simulação à escritura','c':'Acompanhe um caso real consolidado: casal da capital, renda R$ 14 mil, imóvel R$ 420 mil em Caraguatatuba. Entrada de R$ 120 mil (FGTS + poupança), financiamento SFH de R$ 300 mil SAC, parcela inicial ~R$ 3.200 (23% da renda). Processo: pré-análise em 2 bancos, aprovação em 12 dias, ITBI R$ 8.400 (2%), escritura e registro em 45 dias.\n\nLições: a pré-análise em 2 bancos gerou economia de R$ 180/mês na parcela; a documentação do vendedor estava pronta porque o corretor exigiu antes de anunciar; o cliente chegou preparado porque recebeu a planilha de custos no primeiro dia.','p':['Documente 1 caso seu nesse formato (números, prazos, lições)','Use o case na sua apresentação de captação','Compartilhe o case (anonimizado) nas suas redes']} ]} ]}

KB2['TEMPORADA'] = {
 'familia': 'Locação de Temporada e Gestão',
 'modulos': [
  {'t':'O Negócio de Temporada no Litoral','obj':'Entender a economia da temporada e os números que sustentam a operação.','aulas':[
   {'t':'A matemática da temporada: ocupação, ADR e RevPAR','c':'Três números governam a temporada: ADR (diária média), ocupação (% de noites vendidas) e RevPAR (ADR × ocupação — a receita real por imóvel). No litoral paulista, a alta temporada (15/dez a fev + feriados) concentra 50% a 60% da receita anual em ~90 dias.\n\nExemplo real: apartamento de 2 dorm. em Ubatuba, ADR de R$ 700 na alta e R$ 350 na baixa, ocupação anual de 38% → receita bruta ~R$ 62 mil/ano. Custos (plataformas 15-17%, limpeza, manutenção, condomínio, IPTU) consomem 35-45%. Apresentar essa matemática ao proprietário é o que separa o gestor profissional do "amigo que cuida".','p':['Calcule ADR, ocupação e RevPAR de 1 imóvel real','Monte a planilha de receita bruta x custos x líquido','Identifique os 90 dias críticos de receita no seu calendário']},
   {'t':'Lei do Inquilinato e o contrato de temporada','c':'Locação de temporada (até 90 dias, com mobília) é regida pela Lei 8.245/91, art. 48. Diferenças críticas da locação residencial: pode exigir caução e pagamento antecipado, e não há renovação automática. Contrato escrito é obrigatório na prática — com check-in/check-out, regras de condomínio, inventário de mobília e multa por danos.\n\nErro grave comum: usar contrato de locação residencial para temporada. Isso pode caracterizar locação de longo prazo e complicar desocupação. Use modelo específico de temporada, revisado por advogado.','p':['Revise seu contrato: é específico de temporada (Lei 8.245/91, art. 48)?','Inclua inventário fotográfico de mobília como anexo','Defina política de caução e danos por escrito']},
   {'t':'Posicionamento do imóvel: para quem você anuncia','c':'Imóvel de temporada bem posicionado tem público definido: família com crianças (segurança, cozinha, 2 quartos), casal romântico (vista, piscina), grupo de amigos (capacidade, churrasqueira) ou home-office de temporada (internet boa, silêncio). Cada público muda o anúncio, as fotos, o preço mínimo de noites e as regras.\n\nO erro é anunciar "para todo mundo": anúncio genérico converte mal e atrai hóspede errado — o grupo de festa no imóvel de família é o pesadelo que gera reclamação de condomínio e review negativo.','p':['Defina o público principal de cada imóvel da carteira','Reescreva 1 anúncio com foco total nesse público','Ajuste regras (nº mínimo de noites, horários) ao público']} ]},
  {'t':'Precificação Dinâmica','obj':'Maximizar receita com preço que responde à demanda real.','aulas':[
   {'t':'Sazonalidade e calendário de receita','c':'O ano do litoral tem 4 camadas: altíssima (Réveillon, Carnaval — multiplicador 3x a 5x sobre a diária base), alta (jan-fev, feriados prolongados — 1,5x a 2,5x), média (fins de semana de mar-jun e set-nov) e baixa (dias de semana fora de temporada). Quem usa preço fixo o ano inteiro perde receita nos picos e fica vazio na baixa.\n\nMonte o calendário anual antes de abrir as reservas: bloqueie as datas de altíssima com preço premium e estadia mínima (5-7 noites no Réveillon), e libere a baixa com preço agressivo para ocupação.','p':['Monte o calendário anual com as 4 camadas de preço','Defina estadia mínima por camada','Revise o calendário trimestralmente']},
   {'t':'Ferramentas de precificação: PriceLabs e similares','c':'Ferramentas como PriceLabs, Beyond e Wheelhouse cruzam dados de demanda (eventos, feriados, ocupação dos concorrentes, antecedência de busca) e sugerem preço diário por data. O algoritmo captura o que o gestor não vê: um show anunciado em Santos que dobra a busca por aquela data.\n\nMas a ferramenta não substitui o gestor: configure preço base realista, limites mínimo/máximo, e regras de última hora (desconto progressivo a 7, 3 e 1 dia). Revise semanalmente — mercado de temporada muda rápido.','p':['Defina preço base, mínimo e máximo de cada imóvel','Configure regra de desconto de última hora (7/3/1 dia)','Compare 1 semana de preço sugerido x seu histórico']},
   {'t':'Ocupação x tarifa: o equilíbrio que maximiza o ano','c':'Vale mais 38% de ocupação a ADR alta ou 55% a ADR baixa? Faça a conta: RevPAR. No litoral, a resposta muda por camada do ano — na alta, proteja a tarifa (a demanda vem); na baixa, proteja a ocupação (noite vazia é receita zero para sempre).\n\nKPI semanal do gestor: pickup (reservas novas na semana), ocupação futura por mês e comparação com o ano anterior. Decisão de preço sem olhar pickup é chute.','p':['Calcule o RevPAR das 2 estratégias para seu imóvel típico','Crie o relatório semanal de pickup','Defina gatilhos de ação: se ocupação futura < X%, revisar preço']} ]},
  {'t':'Operação e Experiência do Hóspede','obj':'Rodar a operação com padrão hoteleiro e escala.','aulas':[
   {'t':'Check-in, limpeza e manutenção: a operação invisível','c':'A nota do hóspede é construída em 3 momentos: chegada (check-in sem atrito — fechadura eletrônica ou cofre de chave elimina 90% dos problemas), limpeza (padrão hoteleiro: roupa de cama branca, checklist de 40 itens, foto pós-limpeza) e resposta a problemas (chuveiro queimado resolvido em 4h salva a avaliação; em 24h, condena).\n\nMonte a rede local: camareira fixa por região, eletricista e encanador de plantão, estoque de itens críticos. O gestor profissional vende tranquilidade ao proprietário porque tem operação real por trás.','p':['Implante check-in autônomo em 1 imóvel-piloto','Crie o checklist de limpeza de 40 itens','Formalize a rede de fornecedores com contatos de plantão']},
   {'t':'Comunicação automatizada com o hóspede','c':'Régua de mensagens que funciona: confirmação da reserva (boas-vindas + regras), D-3 (endereço, check-in, dicas), dia do check-in (código da fechadura), D+1 (está tudo bem?), check-out (instruções + pedido de avaliação). Automatize com templates no WhatsApp ou nas plataformas — mas mantenha tom humano.\n\nA mensagem D+1 é a mais importante: ela captura o problema antes que ele vire review negativo. Hóspede que reclama e é atendido avalia melhor que hóspede sem problema nenhum.','p':['Escreva os 5 templates da régua','Automatize envio por data de reserva','Institua a regra: toda mensagem de hóspede respondida em <30min']},
   {'t':'Avaliações e reputação: o ativo que compõe juros','c':'Nos portais de temporada, a nota é o ranking: imóveis 4.8+ aparecem primeiro e podem cobrar 10-20% mais. A reputação se constrói com consistência (mesma experiência toda vez) e se protege com resposta profissional a toda avaliação — inclusive às negativas, que respondidas bem viram prova de seriedade.\n\nPeça avaliação no momento de pico de satisfação: logo após o check-out, com link direto. E nunca compre ou fabrique reviews — as plataformas detectam padrões e punem com shadowban.','p':['Defina o ritual do pedido de avaliação pós-checkout','Responda 100% das avaliações em até 48h','Monitore nota média por imóvel mensalmente']} ]},
  {'t':'Plataformas e Distribuição','obj':'Distribuir o imóvel nos canais certos com anúncios que convertem.','aulas':[
   {'t':'Airbnb, Booking e canal direto: a estratégia de canais','c':'Cada canal tem perfil: Airbnb traz volume e público jovem; Booking traz demanda internacional e hóspede de última hora (mas cancelamento maior); canal direto (seu site/WhatsApp) elimina a comissão de 15-17% — mas exige confiança e marketing próprio.\n\nEstratégia saudável: plataformas para ocupação base + canal direto crescendo via repeat guests (hóspede que voltou pagando direto é a margem mais bonita do negócio). Sincronize calendários com channel manager para evitar overbooking — o erro que destrói reputação em 2 canais ao mesmo tempo.','p':['Distribua seu portfólio: % por canal hoje','Crie 1 fluxo de reserva direta para hóspedes recorrentes','Sincronize calendários entre plataformas']} ]} ]}
