KB3 = {}

KB3['INVESTIMENTO'] = {
 'familia': 'Investimento Imobiliário',
 'modulos': [
  {'t':'Fundamentos do Investimento em Imóveis','obj':'Construir a base conceitual para investir com método, não com impulso.','aulas':[
   {'t':'Por que imóvel: retorno, proteção e alavancagem','c':'O imóvel combina três motores que nenhum outro ativo popular entrega junto: renda (aluguel), valorização (longo prazo) e alavancagem (você controla um ativo de R$ 500 mil com R$ 100 mil de entrada e financiamento). No litoral paulista, soma-se um quarto motor: renda de temporada, que em bons imóveis paga o custo de manter e ainda sobra.\n\nMas imóvel tem custos que o entusiasta ignora: liquidez baixa (vender leva meses), custo de transação alto (ITBI, cartório, comissão — 8% a 10% na ponta de compra+venda) e vacância. O investidor profissional só compra quando os números absorvem esses custos.','p':['Liste os 4 motores de retorno de 1 imóvel que você acompanha','Calcule o custo total de transação (compra+venda) dele','Defina seu horizonte mínimo de permanência (regra: 5 anos)']},
   {'t':'Os indicadores essenciais: cap rate, yield e payback','c':'Cap rate = aluguel anual líquido ÷ valor do imóvel. No litoral, imóveis residenciais giram entre 0,35% e 0,55% ao mês de aluguel bruto (4% a 6,5% ao ano); temporada bem operada pode entregar 6% a 10% ao ano líquido, com mais trabalho e risco.\n\nYield bruto engana: desconte IPTU, condomínio, manutenção (regra prática: 5% do valor do imóvel a cada 10 anos) e vacância (1 mês/ano na locação anual). Payback simples = valor ÷ renda líquida anual; acima de 20 anos no residencial exige justificativa pela valorização esperada.','p':['Calcule cap rate bruto e líquido de 2 imóveis reais','Monte planilha com IPTU, condomínio, manutenção e vacância','Defina seu cap rate mínimo de compra']},
   {'t':'Os ciclos do mercado imobiliário do litoral','c':'O mercado do litoral tem dois ciclos sobrepostos: o macro (juros, crédito, renda — financiamento barato infla preços) e o local (obras de infraestrutura, veraneio, lançamentos). Exemplos locais: a duplicação da Tamoios valorizou Caraguatatuba e Ubatuba; o polo de cruzeiros pressionou Santos.\n\nRegra do investidor: compre no ciclo de juros altos (menos competição, vendedores flexíveis) e venda no ciclo de juros baixos. Quem espera "a certeza" compra no topo junto com a manchete de jornal.','p':['Mapeie 2 obras de infraestrutura em andamento nas suas cidades','Acompanhe a taxa básica de juros e o volume de crédito imobiliário','Escreva sua tese de compra para os próximos 24 meses']} ]},
  {'t':'Análise de Oportunidades','obj':'Avaliar imóveis com planilha e critério, não com achismo.','aulas':[
   {'t':'A ficha de análise: 12 dados antes de qualquer proposta','c':'Antes de propor: valor pedido x valor de mercado (comparáveis reais), m² privativo, custo de reforma estimado, IPTU, condomínio, potencial de aluguel anual e de temporada, liquidez do bairro (tempo médio de venda), pendências documentais, zoneamento, riscos ambientais (litoral: recuo de maré, áreas de preservação) e motivação real do vendedor.\n\nA motivação do vendedor vale ouro: inventário, mudança de cidade, imóvel parado há anos — cada uma dessas situações abre espaço real de negociação de 10% a 20%.','p':['Monte sua ficha de análise com os 12 dados','Aplique em 3 imóveis esta semana','Crie o hábito: nenhuma proposta sem ficha completa']},
   {'t':'Onde está o valor no litoral: leitura micro dos bairros','c':'Dentro da mesma cidade, a diferença de retorno entre bairros chega a 3x. Analise: frente-mar x quadra intermediária (frente-mar valoriza mais, mas a quadra do lado tem yield melhor), comércio e serviços andáveis (critério nº 1 de locação), perfil do turista do bairro e estoque de lançamentos (muita oferta nova pressiona o usado).\n\nFerramenta: o mapa de calor pessoal. Rode os bairros em dia de semana à noite — rua vazia às 20h em janeiro é sinal de bairro puramente sazonal; rua viva indica moradia, serviços e liquidez o ano inteiro.','p':['Monte seu mapa de calor: 5 bairros, notas de 0-10 em 5 critérios','Visite 1 bairro-alvo em dia de semana à noite','Compare yield de frente-mar x intermediária em 1 cidade']},
   {'t':'Due diligence documental do investidor','c':'Antes de fechar: matrícula atualizada (ônus, hipotecas, ações), certidões dos vendedores (federais, estaduais, trabalhistas — dívida trabalhista do vendedor pode atingir o imóvel), IPTU e condomínio quitados, habite-se/averbação de construção e, no litoral, verificação de área de marinha (terreno de marinha tem taxa anual e regras próprias).\n\nCusto de uma due diligence com despachante/advogado: R$ 1.500 a R$ 3.000. Custo de pular essa etapa: potencialmente o imóvel inteiro.','p':['Crie seu checklist documental de compra','Tenha 1 despachante e 1 advogado parceiros','Verifique o que é área de marinha nas suas cidades']} ]},
  {'t':'Estratégias de Retorno','obj':'Escolher e executar a estratégia certa para cada perfil de capital.','aulas':[
   {'t':'Renda passiva: locação anual x temporada x mista','c':'Locação anual: renda previsível, menos trabalho, cap rate 4-6%. Temporada: potencial 6-10% líquido, mas exige operação (ou gestora, que cobra 20-30%). Mista: temporada no verão + locação anual fora dela — raro de executar por contrato, mas possível com inquilino que aceita saída em novembro (comum com aposentados que passam o verão com filhos).\n\nA escolha depende do seu tempo e da localização: apartamento a 2 quadras da praia em Guarujá é máquina de temporada; o mesmo capital em bairro residencial de Santos rende melhor em locação anual.','p':['Simule as 3 estratégias para 1 imóvel real','Defina quanto do seu tempo a operação pode consumir','Escolha 1 estratégia padrão e 1 alternativa']},
   {'t':'Valorização forçada: reforma que paga','c':'A reforma certa no litoral: cozinha e banheiro (decidem a compra), pintura clara e piso vinílico (custo baixo, efeito visual alto) e o combate invisível — impermeabilização e esquadrias contra maresia (o comprador experiente do litoral procura isso).\n\nRegra prática: reforma deve custar até 10-15% do valor do imóvel e agregar 20-30% no valor percebido. Reforma de gosto pessoal exagerada não se recupera na venda.','p':['Liste as 5 melhorias de melhor retorno','Peça 2 orçamentos de referência (cozinha e banheiro)','Calcule o ROI esperado de 1 projeto real']},
   {'t':'Compra na planta: o jogo do desconto e do INCC','c':'Comprar na planta no litoral pode render 20-40% até a entrega, mas o risco é real: atraso de obra, correção do saldo pelo INCC (que em ciclos de construção cara come a margem) e revenda difícil antes das chaves.\n\nO investidor profissional só entra com: construtora com histórico de entregas verificável, desconto real sobre a tabela futura (compare com usado pronto no mesmo bairro — a diferença deve compensar o risco de obra), e plano de saída definido (revender na entrega ou renda).','p':['Verifique o histórico de entregas de 2 construtoras locais','Compare preço de planta x pronto em 1 bairro','Simule a evolução do saldo devedor com INCC']} ]},
  {'t':'Portfólio, Financiamento e Saída','obj':'Escalar com alavancagem consciente e planejar a saída desde a compra.','aulas':[
   {'t':'Alavancagem inteligente: usar o banco a seu favor','c':'Financiar um investimento parece contraditório, mas a matemática manda: se o imóvel rende 6% líquido + valorização e o crédito custa ~11% ao ano, o carry é negativo — porém o investidor alavanca o capital próprio e mantém liquidez para a próxima oportunidade.\n\nRegra de segurança: a soma das parcelas não pode depender de ocupação perfeita. Reserve de 6 a 12 meses de parcela antes de alavancar. Quem quebra no imobiliário quebra por fluxo de caixa, não por patrimônio.','p':['Simule 1 compra alavancada com carry negativo explícito','Monte sua reserva de segurança (6-12 parcelas)','Defina seu limite de alavancagem']},
   {'t':'Gestão de portfólio: quando segurar, vender ou trocar','c':'Revise o portfólio anualmente: cada imóvel precisa justificar sua presença (renda, valorização ou uso). O imóvel que valorizou muito e agora tem cap rate comprimido é candidato a venda e rolagem para mercado com yield melhor.\n\nSinais de venda: cap rate líquido abaixo do CDB, manutenção crescente, bairro em declínio relativo. Sinais de hold: infraestrutura chegando, estoque local encolhendo, renda subindo. Decida com planilha, não com apego.','p':['Revise 1 imóvel: hold, vender ou melhorar?','Calcule o cap rate atual pelo valor de mercado de hoje (não o de compra)','Escreva os gatilhos de venda de cada ativo seu']},
   {'t':'Impostos e estrutura: o que o investidor precisa saber','c':'Venda com lucro: ganho de capital de 15% a 22,5% sobre o lucro, com isenções possíveis (único imóvel até R$ 440 mil, venda de residencial para compra de outro em 180 dias). Aluguel recebido por pessoa física: carnê-leão mensal. Holding familiar: reduz custo de sucessão e pode otimizar IR, mas tem custo de manutenção — vale a partir de determinado patrimônio.\n\nErro comum: vender e "esquecer" o ganho de capital — a multa e os juros corroem o lucro. Consulte contador antes da venda, não depois.','p':['Entenda as 2 principais isenções de ganho de capital','Regularize o carnê-leão se recebe aluguel como PF','Consulte 1 contador sobre seu caso específico']} ]} ]}

KB3['MARKETING'] = {
 'familia': 'Marketing Imobiliário e Presença Digital',
 'modulos': [
  {'t':'Posicionamento e Marca Pessoal','obj':'Construir uma marca pessoal que atrai clientes em vez de persegui-los.','aulas':[
   {'t':'Nicho vence generalista: escolha seu território','c':'O corretor "de tudo" compete com milhares; o corretor de "apartamentos frente-mar no Guarujá para famílias" compete com dezenas. Nicho = geografia + perfil de imóvel + perfil de cliente. Quanto mais específico, maior a taxa de conversão e menor o custo de aquisição.\n\nTeste de nicho: em 10 segundos, um estranho deve saber para quem te indicar. "Corretor de imóveis" falha no teste; "especialista em casas de condomínio em Ubatuba para quem sai de SP" passa.','p':['Escreva sua frase de posicionamento (nicho em 1 linha)','Liste os 3 nichos mais rentáveis da sua cidade','Escolha 1 e comprometa 90 dias de conteúdo focado']},
   {'t':'Identidade profissional: foto, bio e prova social','c':'O kit mínimo profissional: foto atual e bem produzida (rosto visível, fundo neutro), bio que fala do resultado para o cliente (não de você), e prova social real — avaliações no Google, depoimentos em vídeo, números de vendas.\n\nNo digital, você é o que o Google mostra. Pesquise seu nome agora: o que aparece? Perfil abandonado ou inconsistente custa vendas silenciosamente. Padronize foto e descrição em todas as redes e no WhatsApp Business.','p':['Google seu nome e documente o resultado','Atualize foto e bio em todas as plataformas hoje','Peça 3 avaliações no Google para clientes satisfeitos']},
   {'t':'Prova social: o multiplicador de confiança','c':'Depoimento vale 10x o que você diz sobre si. Sistema de coleta: peça no pico de satisfação (entrega das chaves, problema resolvido), facilite ao máximo (link direto do Google, roteiro de 3 perguntas para depoimento em vídeo) e publique com autorização.\n\nHierarquia da prova: vídeo de cliente > avaliação Google com nome > print de WhatsApp > sua declaração. Construa o acervo pelos degraus mais altos que conseguir.','p':['Defina o ritual do pedido de depoimento','Colete 2 depoimentos esta semana','Organize o acervo de provas (pasta por tipo)']} ]},
  {'t':'Conteúdo que Vende','obj':'Produzir conteúdo com método: atrair, nutrir e converter.','aulas':[
   {'t':'A pirâmide de conteúdo do corretor','c':'70% conteúdo de valor (bairros, preços médios, documentação, erros de compradores), 20% prova (cases, antes/depois, depoimentos, "vendido"), 10% oferta direta (imóveis à venda). Quem inverte a pirâmide — só posta imóvel — é ignorado, porque ninguém segue catálogo.\n\nFormatos que funcionam no litoral: tour de imóvel em vídeo vertical (primeiros 3 segundos na melhor vista), comparativos de bairros, "quanto custa morar em X" e mitos do financiamento.','p':['Classifique seus últimos 12 posts na pirâmide','Planeje 8 conteúdos de valor para o mês','Grave 1 tour com a regra dos 3 segundos']},
   {'t':'Instagram para corretores: o sistema completo','c':'Rotina mínima eficaz: 3-4 Reels/semana (tours e dicas), Stories diários (bastidores criam confiança), carrossel semanal educativo e destaques organizados (Vendas, Bairros, Depoimentos, Sobre mim).\n\nMétricas que importam: salvamentos e compartilhamentos (interesse real), respostas aos Stories (leads quentes) e cliques no link. Curtida é vaidade. E consistência vence perfeição: conta que posta 3x por semana por 6 meses supera a que faz 15 posts perfeitos em janeiro e some.','p':['Organize os 4 destaques do perfil','Estabeleça o calendário mínimo semanal','Revise métricas certas toda segunda-feira']},
   {'t':'SEO local: ser encontrado por quem já quer comprar','c':'Quem busca "apartamento 2 quartos Praia Grande" tem intenção de compra — diferente do scroll do Instagram. As bases do SEO local imobiliário: Perfil de Empresa no Google completo e com avaliações, páginas por bairro/cidade no seu site e conteúdo respondendo dúvidas reais (preço médio, documentação, financiamento).\n\nResultado de SEO leva 3-6 meses, mas depois compõe: o artigo que responde "documentação para comprar imóvel na praia" traz leads todos os meses, de graça, por anos.','p':['Complete 100% do Perfil de Empresa no Google','Liste 10 dúvidas reais que clientes te perguntam','Produza 1 conteúdo por semana respondendo cada uma']} ]},
  {'t':'Anúncios Pagos e Conversão','obj':'Investir em tráfego com retorno mensurável.','aulas':[
   {'t':'Meta Ads para imobiliárias: estrutura de campanha','c':'Estrutura enxuta que funciona: campanha de leads com segmentação por raio nas cidades-alvo (inclua SP capital para imóveis de temporada — o comprador mora lá), criativo em vídeo do imóvel real e formulário com 3-4 perguntas de qualificação (orçamento, prazo, uso).\n\nErros que queimam verba: impulsionar post (botão azul) sem estrutura, segmentar "interesse em imóveis" (audiência fria e genérica) e formulário sem qualificação (lead de R$ 3 que não atende telefone). Meta de referência: custo por lead qualificado de R$ 8 a R$ 25 no litoral, dependendo do ticket.','p':['Pare todo impulsionamento sem estrutura hoje','Monte 1 campanha com formulário de qualificação','Meça custo por lead qualificado, não por lead bruto']},
   {'t':'Landing pages e captura: o destino do anúncio','c':'Nunca mande tráfego pago para a home do site. Cada campanha precisa de página específica: título com a promessa, 3 provas (fotos reais, números, depoimento), formulário curto e WhatsApp visível.\n\nTeste o essencial: título (o maior alavancador), imagem principal e número de campos do formulário. A cada 100 visitas, uma landing boa de imobiliário converte 5 a 15 leads; abaixo de 3, há problema de página ou de público.','p':['Audite: seus anúncios levam a páginas específicas?','Reduza seu formulário a 4 campos','Registre a taxa de conversão semanal']},
   {'t':'WhatsApp Business: o motor de conversão','c':'No Brasil, a venda imobiliária se fecha no WhatsApp. Configure o Business: catálogo com imóveis em destaque, respostas rápidas para as 10 perguntas frequentes, etiquetas por etapa do funil e mensagem de ausência.\n\nRegra de ouro: WhatsApp é canal de conversa, não de despejo — nada de listas de transmissão diárias com 20 imóveis. Envio segmentado (lead de temporada recebe temporada) e com contexto ("vi que você se interessou por X, surgiu Y no mesmo condomínio") converte; spam bloqueia.','p':['Configure catálogo e respostas rápidas','Implante etiquetas por etapa do funil','Substitua transmissão em massa por envio segmentado']} ]},
  {'t':'Métricas e Rotina de Crescimento','obj':'Transformar marketing em sistema mensurável e previsível.','aulas':[
   {'t':'O painel mínimo de marketing do corretor','c':'Cinco números por semana: alcance, leads gerados, custo por lead, leads qualificados e vendas originadas. Com eles você calcula o que importa: quanto custa uma venda no seu marketing e qual canal merece mais recurso.\n\nRegra de alocação: 70% do orçamento no canal que já produz venda, 20% no segundo melhor, 10% em experimentos. Marketing sem número é hobby; com número, é investimento.','p':['Monte o painel de 5 números (planilha simples)','Calcule seu custo por venda atual por canal','Realoque o orçamento na regra 70/20/10']},
   {'t':'Rotina semanal de marketing em 3 horas','c':'Marketing sustentável para quem vende: segunda (1h) — revisar métricas e planejar a semana; quarta (1h) — produzir o conteúdo principal; sexta (1h) — agendar posts e responder comentários acumulados. O resto é Stories no fluxo do dia (bastidores custam zero horas extras).\n\nBatching é o segredo: produzir 3 Reels em uma única manhã de visitas custa muito menos que 3 produções separadas. Grave sempre que estiver em um imóvel bonito.','p':['Bloqueie as 3 horas semanais na agenda','Adote batching: grave 3 conteúdos por sessão','Use dias de visita como fonte de bastidores']},
   {'t':'Case de marketing real no litoral','c':'Síntese de caso típico: corretora de Caraguatatuba parou de impulsionar fotos de imóveis e passou a publicar 3 Reels semanais de tours + conteúdo de bairros. Em 5 meses: perfil saiu de 800 para 4.200 seguidores locais, 30% dos leads passaram a vir do Instagram (custo zero), e o custo por lead das campanhas pagas caiu 40% porque os criativos viraram os tours que já performavam no orgânico.\n\nLições: orgânico bom alimenta o pago (teste criativos no orgânico primeiro), conteúdo local supera conteúdo genérico e constância de 5 meses é o preço de entrada do resultado.','p':['Teste seus criativos no orgânico antes de pagar','Defina o compromisso mínimo de 5 meses','Documente sua evolução mês a mês']} ]} ]}
