KB5 = {}

KB5['TECNOLOGIA'] = {
 'familia': 'Tecnologia e IA para o Mercado Imobiliário',
 'modulos': [
  {'t':'Ferramentas Essenciais do Corretor Digital','obj':'Montar o stack mínimo de tecnologia que multiplica produtividade.','aulas':[
   {'t':'CRM: o sistema nervoso da operação','c':'CRM imobiliário não é planilha de contatos — é funil visual com régua de follow-up. O mínimo necessário: registro de todo contato, etapa do funil clara, lembretes automáticos de retorno e histórico de interações. Sem CRM, o follow-up depende de memória — e memória falha no 4º contato, exatamente onde acontecem as vendas.\n\nO critério de escolha: você vai usar todos os dias? Um CRM simples usado sempre vence um sofisticado abandonado.','p':['Migre 100% dos contatos ativos para o CRM esta semana','Defina as etapas do seu funil (máx. 7)','Configure lembretes automáticos de follow-up']},
   {'t':'Automação de rotinas: o que delegar para a máquina','c':'Automatize o repetitivo, personalize o decisivo. Automatizáveis: resposta de primeiro contato, envio de materiais pós-visita, lembretes de follow-up, relatório quinzenal ao proprietário e aniversários. Humanos: negociação, visitas, conversas difíceis e fechamento.\n\nCada hora semanal automatizada é uma hora para atender mais um cliente.','p':['Liste suas 5 tarefas mais repetitivas da semana','Automatize 1 delas esta semana','Meça o tempo economizado no fim do mês']},
   {'t':'Fotos e mídia profissional com o celular','c':'A foto vende a visita. Regras de ouro: luz natural (fotografe no horário de melhor luz do imóvel), horizontalidade (celular nivelado), cantos de cômodo (ampliam o espaço) e limpeza de cena (sem objetos pessoais). Vídeo tour vertical de 30-60 segundos começando pelo ponto mais forte.\n\nInvestimento que se paga em semanas: lente grande-angular clipada ao celular e um tripé com nível. Edição leve (brilho, horizonte) — nunca filtros que distorcem cores: o cliente que chega e encontra o imóvel diferente das fotos perde a confiança em tudo.','p':['Fotografe 1 imóvel seguindo as 4 regras','Monte o kit básico (lente + tripé)','Padronize: 10-15 fotos + 1 tour vertical por imóvel']} ]},
  {'t':'IA Aplicada ao Dia a Dia','obj':'Usar inteligência artificial como assistente produtiva, com revisão humana.','aulas':[
   {'t':'IA para descrições e conteúdo de imóveis','c':'A IA gera em segundos o que levava uma hora: descrição de anúncio, post de rede social, resposta a perguntas frequentes. O fluxo profissional: dê à IA a ficha técnica do imóvel (dormitórios, m², diferenciais, bairro) + o público-alvo + o tom desejado; receba o rascunho; revise dados e personalize.\n\nRegra inviolável: a IA escreve, você confere. Erro de dado em anúncio (metragem errada, condomínio inventado) vira problema jurídico. Use a IA para velocidade e estilo; a responsabilidade pelo fato é sua.','p':['Crie seu prompt padrão de descrição (ficha + público + tom)','Gere e revise 3 descrições hoje','Compare tempo: antes x com IA']},
   {'t':'IA para qualificação e atendimento inicial','c':'Assistentes de IA podem conduzir o primeiro atendimento 24/7: responder sobre o imóvel, qualificar (orçamento, prazo, perfil) e agendar visita. O lead das 23h de domingo é atendido na hora — e chega qualificado para você na segunda de manhã.\n\nCuidados: deixe claro que é um assistente virtual, defina o ponto de transferência para humano (proposta, negociação, reclamação) e revise semanalmente as conversas para corrigir respostas. IA mal configurada promete o que o imóvel não tem.','p':['Mapeie as 10 perguntas que todo lead faz','Defina os pontos de transferência obrigatória para humano','Revise conversas semanalmente nos primeiros 60 dias']},
   {'t':'Análise de dados com IA: decisões mais rápidas','c':'Use IA para ler dados: cole sua planilha de leads e peça padrões ("qual origem converte mais?", "em qual etapa perco mais leads?"), ou peça comparativos de bairros com os dados que você coletou. A IA enxerga padrões que a planilha esconde.\n\nLimite importante: a IA só analisa o que você fornece — dado ruim gera conclusão ruim. Mantenha o CRM limpo e padronizado para que a análise valha alguma coisa.','p':['Exporte seus dados de leads e peça 3 análises à IA','Padronize os campos do CRM (origem, etapa, motivo de perda)','Tome 1 decisão do mês baseada nesses dados']} ]},
  {'t':'Segurança Digital e LGPD','obj':'Proteger dados de clientes e a operação digital.','aulas':[
   {'t':'LGPD na prática do corretor','c':'Você coleta dados pessoais sensíveis (renda, documentos, CPF). A LGPD exige: finalidade clara (coletar só o necessário para a negociação), segurança (senhas, dispositivos protegidos, nada de documentos em grupo de WhatsApp) e direito do titular (se pedir para apagar, apague).\n\nPrática segura: pasta digital por cliente com acesso restrito, compartilhamento por link com validade, e política simples informando como os dados são usados. Vazamento de dados de clientes é dano de reputação que não se recupera.','p':['Audite onde estão os documentos dos clientes hoje','Pare de receber documentos por WhatsApp sem organização','Escreva sua política de uso de dados em 5 linhas']},
   {'t':'Segurança das contas: o básico que evita o desastre','c':'Ative verificação em duas etapas em WhatsApp, e-mail, redes sociais e banco — sem exceção. Senha única por serviço (gerenciador de senhas resolve). E cuidado com o golpe do WhatsApp clonado, comum contra corretores: o golpista se passa por você e pede "taxa de reserva" aos seus clientes.\n\nPrevina com comunicação proativa: informe no primeiro contato que você nunca pede valores por WhatsApp antes de contrato, e qual é seu número oficial. Cliente avisado não cai.','p':['Ative 2FA em todas as contas hoje','Instale um gerenciador de senhas','Inclua o aviso anti-golpe no primeiro atendimento']},
   {'t':'Backup e continuidade: seu negócio não cabe em um celular','c':'Sua carteira de contatos, contratos e histórico de clientes é seu ativo mais valioso — e provavelmente está em um único celular. Regra 3-2-1: 3 cópias, 2 mídias, 1 fora (nuvem). Backup automático de fotos e conversas, exportação mensal do CRM e documentos em nuvem com acesso de segundo fator.\n\nTeste o desastre antes dele: e se o celular sumir hoje? Se a resposta envolve pânico, seu plano de continuidade ainda não existe.','p':['Ative backup automático de fotos e conversas','Exporte o CRM mensalmente','Faça o teste do celular perdido (mentalmente)']} ]},
  {'t':'Tecnologia na Experiência do Cliente','obj':'Usar tecnologia para encantar: tours, assinatura digital e processos sem atrito.','aulas':[
   {'t':'Tour virtual e visita remota: vendendo a distância','c':'Grande parte dos compradores do litoral mora longe. O tour bem feito — vídeo guiado ao vivo por videochamada ou tour 360° — qualifica antes da visita presencial: quem vem depois do tour já vem quase decidido.\n\nRoteiro do tour ao vivo: comece pela vista/ponto forte, mostre os pontos fracos proativamente (transparência gera confiança), termine na rua e no entorno. Grave (com permissão) para o cliente compartilhar com a família — decisão imobiliária é coletiva.','p':['Faça 1 tour ao vivo por videochamada esta semana','Defina o roteiro padrão do tour','Teste 1 ferramenta de tour 360° em um imóvel']},
   {'t':'Assinatura digital e documentos sem papel','c':'Contratos com assinatura eletrônica (plataformas reconhecidas) têm validade jurídica e aceleram dias em horas — essencial quando o proprietário mora na capital e o comprador em outra cidade. Organize o fluxo: documento revisado → envio para assinatura → confirmação → arquivo em pasta digital do processo.\n\nCombine com videoconferência para dúvidas: o pacote completo remoto (tour + proposta + assinatura) viabiliza vendas que antes morriam na logística de encontros.','p':['Escolha 1 plataforma de assinatura eletrônica','Monte o fluxo de assinatura remota passo a passo','Teste o fluxo completo em 1 operação']} ]} ]}

KB5['PRODUTIVIDADE'] = {
 'familia': 'Produtividade, Gestão e Carreira',
 'modulos': [
  {'t':'Gestão do Tempo do Corretor','obj':'Recuperar o controle da agenda em uma profissão sem horário fixo.','aulas':[
   {'t':'A semana ideal do corretor','c':'Sem estrutura, a semana do corretor vira reação a urgências. O modelo validado divide a semana em blocos: prospecção (manhãs de segunda e terça — horário nobre, mente fresca), atendimentos e visitas (tarde), follow-ups (bloco fixo diário de 45 min) e administração (sexta de manhã).\n\nRegra dos blocos: prospecção na agenda é compromisso com cliente invisível — o de mês que vem. Quem não protege o bloco de prospecção tem mês bom seguido de mês vazio, eternamente.','p':['Desenhe sua semana ideal com os 4 blocos','Bloqueie prospecção como compromisso inegociável','Revise na sexta: o que vazou e por quê']},
   {'t':'Priorização: o urgente contra o importante','c':'A matriz simples: urgente+importante (proposta em negociação) você faz; importante não urgente (prospecção, conteúdo, estudo) você agenda; urgente não importante (metade das mensagens) você delega ou limita; e o resto você elimina.\n\nA métrica da verdade: quanto do seu dia foi em atividade que gera receita (conversa com cliente, visita, negociação, prospecção)? Abaixo de 40%, o problema não é falta de tempo — é alocação.','p':['Registre 3 dias de atividades e classifique na matriz','Calcule seu % de tempo em atividade de receita','Elimine ou delegue 2 atividades da semana']},
   {'t':'Rotinas que sustentam a consistência','c':'O corretor consistente tem rituais: abertura do dia (15 min: agenda, follow-ups pendentes, meta do dia), bloco de follow-up sagrado e fechamento do dia (10 min: o que avançou, o que trava amanhã).\n\nConsistência vence intensidade: 10 contatos de prospecção por dia, todo dia, geram ~200/mês — mais que o "dia da prospecção maratona" seguido de duas semanas de silêncio.','p':['Institua a abertura e o fechamento do dia','Defina sua meta diária mínima de contatos','Marque o bloco diário de follow-up na agenda']} ]},
  {'t':'Finanças Pessoais do Corretor Autônomo','obj':'Organizar a renda variável para ela não controlar você.','aulas':[
   {'t':'Vivendo com renda variável: o sistema de 3 contas','c':'A renda do corretor é irregular — o sistema resolve: conta 1 (essencial): salário mensal fixo que você se paga, calculado pela média dos 12 meses; conta 2 (reserva): meses bons alimentam 3-6 meses de custo; conta 3 (impostos e reinvestimento): percentual de cada comissão separado no dia do recebimento.\n\nO erro clássico: viver o padrão do melhor mês. Janeiro de alta temporada paga fevereiro fraco — quem gasta em janeiro como se todo mês fosse janeiro, quebra em março.','p':['Calcule sua média de renda dos últimos 12 meses','Defina seu salário mensal fixo','Separe o percentual de reserva/impostos da próxima comissão no dia']},
   {'t':'Precificando o próprio trabalho','c':'Corretor autônomo precisa saber seu custo-hora real: some custos fixos (transporte, telefone, marketing, ferramentas) + salário-alvo, divida pelas horas produtivas. Esse número disciplina decisões: vale fazer aquela visita de 2h para um lead desqualificado? Quando você conhece seu custo-hora, o "sim" indiscriminado acaba.\n\nO mesmo cálculo vale para imóveis da carteira: captação que consome 40 horas e não vende custou caro — a curva ABC da carteira é também uma decisão financeira.','p':['Calcule seu custo-hora real','Aplique o custo-hora na decisão de 3 compromissos desta semana','Revise a carteira sob a ótica de horas investidas']} ]},
  {'t':'Carreira e Especialização','obj':'Construir uma carreira que valoriza com o tempo.','aulas':[
   {'t':'De generalista a referência: o caminho da especialização','c':'O corretor que domina um nicho (temporada de alto padrão, aposentados, investidores) cobra melhor, recebe indicação qualificada e sofre menos com concorrência. A especialização se constrói com: conhecimento profundo (cursos, dados locais), presença (conteúdo no nicho) e cases documentados.\n\nCronograma realista: 6-12 meses para ser reconhecido no nicho, 24 meses para ser a referência. O atalho não existe — mas a consistência acelera.','p':['Escolha seu nicho de especialização','Defina o plano de 12 meses (conhecimento, presença, cases)','Documente seu primeiro case do nicho']},
   {'t':'Networking profissional: sua rede é seu estoque','c':'Advogados, contadores, gerentes de banco, síndicos, administradoras e outros corretores (parcerias 50/50 em imóveis fora da sua área) formam a rede que alimenta sua carteira. Cada relacionamento profissional vale captações indiretas por anos.\n\nRegra do networking útil: dê antes de pedir. Envie o cliente que precisa de contador para o contador; a recíproca vem. Participe de 1 evento ou associação local por mês — com follow-up real depois.','p':['Liste sua rede atual e os 5 perfis que faltam','Faça 1 contato de valor (sem pedir nada) esta semana','Agende 1 evento local por mês']},
   {'t':'Aprendizado contínuo: o corretor que não para','c':'O mercado muda (juros, regras, tecnologia, plataformas) e a estante parada desvaloriza. Sistema mínimo: 30 min diários de estudo (legislação, técnica de vendas, dados do mercado local), 1 curso estruturado por trimestre e revisão mensal dos próprios resultados — o melhor professor é seu funil.\n\nDocumente o aprendizado: cada conceito novo vira um teste prático na semana seguinte. Conhecimento não aplicado em 30 dias é esquecido.','p':['Bloqueie os 30 min diários de estudo','Escolha o curso do trimestre','Regra: todo conceito novo vira teste prático em 7 dias']} ]},
  {'t':'Oratória e Comunicação Profissional','obj':'Comunicar com clareza em visitas, negociações e vídeos.','aulas':[
   {'t':'Falar bem vende mais: estrutura e clareza','c':'Boa comunicação imobiliária é estrutura, não dom: prepare a abertura (o que o cliente ganha ouvindo você), desenvolva em 3 pontos (mais que 3, ninguém retém) e feche com próximo passo claro.\n\nEm vídeo, as mesmas regras + 2: os primeiros 3 segundos decidem (comece no ponto forte) e fale olhando a lente como se fosse o cliente. Grave, assista, corte o que não agrega. Os primeiros 20 vídeos serão medianos — os próximos 20 vão te diferenciar de 95% do mercado.','p':['Estruture sua próxima apresentação em 3 pontos','Grave 1 vídeo curto seguindo as regras','Peça feedback honesto a 1 colega']},
   {'t':'Apresentações para grupos e parceiros','c':'Apresentar para uma administradora de condomínios ou uma equipe de vendas exige versão ampliada da mesma estrutura: problema da audiência (não o seu serviço), evidência (case com números), proposta clara e chamada única para ação.\n\nPrepare-se com a regra 10-20-30 adaptada: até 10 slides, 20 minutos, sem texto menor que o legível. Ensaie em voz alta 2 vezes — a segunda versão é sempre 30% melhor.','p':['Monte sua apresentação institucional de 10 slides','Ensaie em voz alta 2 vezes','Ofereça 1 apresentação para 1 administradora este mês']} ]} ]}
