@echo off
cd /d "%~dp0.."
echo Abrindo painel de execucao diaria...
start "" "docs/sales/painel-execucao-diaria-praia-digital-2026.html"
echo Abrindo centro de comando...
start "" "docs/sales/centro-comando-prospeccao-praia-digital-2026.html"
echo Abrindo roteiro omnichannel...
start "" "docs/sales/roteiro-prospeccao-omnichannel-praia-digital-2026.html"
echo Abrindo templates Brevo...
start "" "outreach/email-first-contact-brevo-lote-30-2026-07-10.html"
echo Abrindo WhatsApp Top 5...
start "" "outreach/whatsapp-top5-leads-litoral-2026.html"
echo Abrindo kit de valores...
start "" "docs/sales/kit-valores-prospeccao-praia-digital-2026.html"
echo.
echo Tudo aberto. Faca os envios e atualize o tracker apos cada envio.
pause
