#!/usr/bin/env python3
# Fase 4 — Consolidacao de conteudo (2026-09-24)
# Posts de blog SEM impressoes no GSC (28d) recebem canonical para o guia-pilar
# do seu tema. Posts com impressoes (KEEP) sao preservados intactos.
import os, re

BASE = 'https://praia.digital/'

PILLARS = [
    (re.compile(r'airbnb|booking|temporada|hosped|anuncio', re.I), 'guias/aluguel-temporada-airbnb-litoral-sp.html'),
    (re.compile(r'financiamento|consorcio|fgts|portabilidade|lance-embutido|carta-credito|refinanciamento|minha-casa', re.I), 'guias/financiamento-consorcio-imovel-litoral.html'),
    (re.compile(r'iptu|itbi|taxa|aforamento|imposto|ganho-de-capital|escritura|custos|inss', re.I), 'guias/impostos-custos-imovel-litoral.html'),
    (re.compile(r'corretor|imobiliaria|captacao|leads|marketing|seo|branding|creci|prospeccao|comissoes|crm|meta-ads|avaliacoes-google|palavras-chave|whatsapp-litoral|onboarding-parceiro|case-de-sucesso|cases', re.I), 'guias/marketing-imobiliario-corretores-litoral.html'),
    (re.compile(r'invest|rentabilidade|roi|valorizacao|predicao|preco-m2', re.I), 'guias/investir-imoveis-litoral-paulista.html'),
    (re.compile(r'ubatuba|caraguatatuba|sao-sebastiao|ilhabela|litoral-norte', re.I), 'guias/litoral-norte-imoveis.html'),
    (re.compile(r'santos|guaruja|praia-grande|sao-vicente|itanhaem|mongagua|peruibe|bertioga|riviera|baixada|ilha-comprida|cananeia', re.I), 'guias/baixada-santista-imoveis.html'),
    (re.compile(r'compra|comprar|documento|matricula|usucapiao|heranca|permuta|casamento|planta|reformado|vender|venda', re.I), 'guias/comprar-imovel-litoral.html'),
]

KEEP = {
    'https://praia.digital/',
    'https://praia.digital/assets/ferramentas/recomendacao-automatica-imoveis-litoral-2026.html',
    'https://praia.digital/assets/qualificador-leads-imobiliario.html',
    'https://praia.digital/assets/simulador-receita-ia-imobiliaria.html',
    'https://praia.digital/bairros/ilhabela/index.html',
    'https://praia.digital/bairros/ilhabela/pernambuco.html',
    'https://praia.digital/bairros/itanhaem/jardim-sao-paulo.html',
    'https://praia.digital/bairros/itanhaem/vila-sao-joao.html',
    'https://praia.digital/bairros/santos/index.html',
    'https://praia.digital/bairros/sao-vicente/jardim.html',
    'https://praia.digital/blog/',
    'https://praia.digital/blog/Segmento-aluguel-temporada-litoral-2026.html',
    'https://praia.digital/blog/abordagem-proprietarios-whatsapp-litoral-2026.html',
    'https://praia.digital/blog/administracao-imoveis-longe-litoral-paulista-2026.html',
    'https://praia.digital/blog/agenda-de-eventos-shows-vida-noturna-riviera-bertioga-2026.html',
    'https://praia.digital/blog/agentes-autonomos-por-que-praia-digital-2026.html',
    'https://praia.digital/blog/airbnb-vs-booking-litoral-sp.html',
    'https://praia.digital/blog/aluguel-temporada-honorarios-corretor-como-calcular-2026.html',
    'https://praia.digital/blog/aluguel-temporada-litoral-honorarios-sucumbencia-2026.html',
    'https://praia.digital/blog/aluguel-temporada-litoral-hospede-frequente-fidelidade-2026.html',
    'https://praia.digital/blog/aluguel-temporada-litoral-manutencao-piscina-2026.html',
    'https://praia.digital/blog/aluguel-temporada-litoral-multa-rescisao-contrato-2026.html',
    'https://praia.digital/blog/aluguel-temporada-litoral-reserva-cancelamento-2026.html',
    'https://praia.digital/blog/aluguel-temporada-litoral-sazonalidade-estrategia-2026.html',
    'https://praia.digital/blog/analise-mercado-imobiliario-litoral-2026.html',
    'https://praia.digital/blog/analise-mercado-imobiliario-litoral-paulista-2026.html',
    'https://praia.digital/blog/anuncios-facebook-instagram-imoveis-litoral-2026.html',
    'https://praia.digital/blog/anuncios-imoveis-litoral-paulista-2026.html',
    'https://praia.digital/blog/apartamento-costa-verde-2026.html',
    'https://praia.digital/blog/apresentacao-video-imoveis-vender-mais-2026.html',
    'https://praia.digital/blog/apto-aposentado-sao-vicente-ia.html',
    'https://praia.digital/blog/assinatura-profissional-corretores-litoral-2026.html',
    'https://praia.digital/blog/avaliacoes-google-imobiliarias-litoral-reputacao-local-2026.html',
    'https://praia.digital/blog/bairros/index.html',
    'https://praia.digital/blog/bertioga-artigo-juridico-imoveis-2026.html',
    'https://praia.digital/blog/bertioga-artigo-marketing-digital-imoveis-2026.html',
    'https://praia.digital/blog/bertioga-crescendo-transformacao-2026.html',
    'https://praia.digital/blog/bertioga-curso-corretor-imoveis-2026.html',
    'https://praia.digital/blog/bertioga-curso-parcerias-imoveis-2026.html',
    'https://praia.digital/blog/bertioga-ou-riviera-sao-lourenco-investir-2026.html',
    'https://praia.digital/blog/bertioga-perspectivas-mercado-imobiliario-2026.html',
    'https://praia.digital/blog/bertioga-riviera-de-sao-lourenco-investimento-2026.html',
    'https://praia.digital/blog/bertioga-temporada-gestao-imoveis-2026.html',
    'https://praia.digital/blog/branding-pessoal-corretor-imoveis-autoridade-2026.html',
    'https://praia.digital/blog/canais-prospeccao-imoveis-litoral-2026.html',
    'https://praia.digital/blog/caraguatatuba-artigo-juridico-imoveis-2026.html',
    'https://praia.digital/blog/caraguatatuba-artigo-marketing-digital-imoveis-2026.html',
    'https://praia.digital/blog/caraguatatuba-curso-corretor-imoveis-2026.html',
    'https://praia.digital/blog/carta-credito-imobiliaria-como-funciona-2026.html',
    'https://praia.digital/blog/carteira-imoveis-aluguel-temporada-litoral-2026.html',
    'https://praia.digital/blog/case-de-sucesso-imobiliaria-santos-litoral-2026.html',
    'https://praia.digital/blog/casos-hermes-agents-2026.html',
    'https://praia.digital/blog/checklist-captacao-imoveis-litoral-21-passos-2026.html',
    'https://praia.digital/blog/checklist-compra-praia-grande-2026.html',
    'https://praia.digital/blog/como-chegar-na-riviera-de-sao-lourenco-rotas-dicas-2026.html',
    'https://praia.digital/blog/compra-imovel-litoral-imovel-reformado-riscos-2026.html',
    'https://praia.digital/blog/construcao-imovel-litoral-legalidade-2026.html',
    'https://praia.digital/blog/contrato-aluguel-temporada-litoral-clausulas-2026.html',
    'https://praia.digital/blog/custos-imovel-praia.html',
    'https://praia.digital/blog/dashboard-imobiliario-litoral-pratico-2026.html',
    'https://praia.digital/blog/documentacao-aluguel-temporada-litoral-checklist-2026.html',
    'https://praia.digital/blog/documentacao-certidoes-financiamento-imobiliario-2026.html',
    'https://praia.digital/blog/documentos-compra-imovel-litoral-2026.html',
    'https://praia.digital/blog/escritura-imovel-litoral-passos-custos-2026.html',
    'https://praia.digital/blog/estudo-rental-yield-apartamentos-1-2-dormitorios-praia-grande-2026.html',
    'https://praia.digital/blog/fgts-segunda-moradia-litoral-2026.html',
    'https://praia.digital/blog/financiamento-caixa-imoveis-litoral-2026.html',
    'https://praia.digital/blog/financiamento-imobiliario-litoral-fgts-2026.html',
    'https://praia.digital/blog/financiamento-imovel-litoral.html',
    'https://praia.digital/blog/financiamento-imovel-praia-documentacao-aprovar.html',
    'https://praia.digital/blog/financiamento-primeiro-imovel-litoral-sp-2026.html',
    'https://praia.digital/blog/financiamento-terreno-litoral-sp-regras-2026.html',
    'https://praia.digital/blog/fotografia-aerea-drone-imoveis-litoral.html',
    'https://praia.digital/blog/gestao-comissoes-equipe-imobiliaria-litoral-2026.html',
    'https://praia.digital/blog/gestao-profissional-imoveis-litoral-paulista-2026.html',
    'https://praia.digital/blog/guaruja-enseada-vs-pitangueiras-investimento-2026.html',
    'https://praia.digital/blog/guaruja-tendencias-imoveis-2027.html',
    'https://praia.digital/blog/guia-beach-tennis-tenis-esportes-raquete-riviera-bertioga-2026.html',
    'https://praia.digital/blog/guia-churrasco-area-gourmet-utilidades-riviera-2026.html',
    'https://praia.digital/blog/guia-cuidados-pele-cabelo-praia-protetor-pos-sol-anti-uv-2026.html',
    'https://praia.digital/blog/guia-desumidificador-antimofo-ventiladores-casa-praia-2026.html',
    'https://praia.digital/blog/guia-ecoturismo-trilhas-cachoeiras-bertioga-riviera-2026.html',
    'https://praia.digital/blog/guia-equipamentos-praia-premium-acessorios-luxo-riviera-2026.html',
    'https://praia.digital/blog/guia-estudo-creci-2026.html',
    'https://praia.digital/blog/guia-filtros-purificadores-tratamento-agua-praia-riviera-2026.html',
    'https://praia.digital/blog/guia-geradores-silenciosos-energia-portatil-nobreaks-praia-riviera-2026.html',
    'https://praia.digital/blog/guia-iluminacao-externa-paisagismo-anti-maresia-riviera-2026.html',
    'https://praia.digital/blog/guia-pet-friendly-riviera-sao-lourenco-bertioga-2026.html',
    'https://praia.digital/blog/guia-pratico-ia-imobiliaria-litoral-paulista.html',
    'https://praia.digital/blog/hermes-agents-como-funcionam-2026.html',
    'https://praia.digital/blog/hermes-agents-implementacao-pratica.html',
    'https://praia.digital/blog/hermes-agents-vs-concorrentes-2026.html',
    'https://praia.digital/blog/ilha-comprida-bairros-imoveis-2026.html',
    'https://praia.digital/blog/ilha-comprida-investimento-imoveis-2026.html',
    'https://praia.digital/blog/ilha-comprida-rentabilidade-imoveis-2026.html',
    'https://praia.digital/blog/imovel-adquirido-antes-casamento-divisao-bens-2026.html',
    'https://praia.digital/blog/imovel-litoral-aluguel-temporada-checkin-2026.html',
    'https://praia.digital/blog/imovel-litoral-aluguel-temporada-dicas-anfitriao-2026.html',
    'https://praia.digital/blog/imovel-litoral-construcao-terreno-lamina-planejamento-2026.html',
    'https://praia.digital/blog/imovel-litoral-contrato-aluguel-fiador-exigencia-2026.html',
    'https://praia.digital/blog/imovel-litoral-contrato-aluguel-modelo-2026.html',
    'https://praia.digital/blog/imovel-litoral-direito-vizinhanca-obras-2026.html',
    'https://praia.digital/blog/imovel-litoral-documentacao-compra-estrangeiro-2026.html',
    'https://praia.digital/blog/imovel-litoral-financiamento-aprovacao-2026.html',
    'https://praia.digital/blog/imovel-litoral-inss-obra-calculo-2026.html',
    'https://praia.digital/blog/imovel-litoral-precificacao-aluguel-temporada-2026.html',
    'https://praia.digital/blog/imovel-litoral-risco-alagamento-prevencao-2026.html',
    'https://praia.digital/blog/impostos-compra-imovel-litoral-2026.html',
    'https://praia.digital/blog/indicadores-pdi-imobiliaria-litoral-2026.html',
    'https://praia.digital/blog/investimento-guaruja-2026.html',
    'https://praia.digital/blog/investimento-imoveis-ilhabela-2026.html',
    'https://praia.digital/blog/investir-bertioga-regioes-2026.html',
    'https://praia.digital/blog/investir-imoveis-litoral-paulista-2026.html',
    'https://praia.digital/blog/itanhaem-artigo-cases-imoveis-2026.html',
    'https://praia.digital/blog/itanhaem-centro-antigo-lagoa-2026-sp-2026-07-14.html',
    'https://praia.digital/blog/itanhaem-curso-corretor-imoveis-2026.html',
    'https://praia.digital/blog/itbi-registro-imoveis-santos-guaruja-bertioga-2026.html',
    'https://praia.digital/blog/lancamento-imobiliario-litoral-2026.html',
    'https://praia.digital/blog/lancamentos-imobiliarios-na-planta-litoral-2026.html',
    'https://praia.digital/blog/lead-magnet-imobiliarias-litoral-2026.html',
    'https://praia.digital/blog/legislacao-ambiental-imoveis-litoral-app-marinha-2026.html',
    'https://praia.digital/blog/machine-learning-imoveis-litoral.html',
    'https://praia.digital/blog/manutencao-preventiva-imovel-praia-maresia-2026.html',
    'https://praia.digital/blog/marketing-digital-imobiliarias-praia-grande-2026.html',
    'https://praia.digital/blog/marketing-imobiliario-litoral-redes-sociais-2026.html',
    'https://praia.digital/blog/melhor-epoca-para-visitar-riviera-de-sao-lourenco-2026.html',
    'https://praia.digital/blog/meta-ads-imobiliarias-litoral-facebook-instagram-2026.html',
    'https://praia.digital/blog/modelo-contrato-aluguel-temporada-litoral.html',
    'https://praia.digital/blog/mongagua-case-sucesso-cases-imoveis-2026.html',
    'https://praia.digital/blog/negociacao-corretores-parceiros-lancamentos-2026.html',
    'https://praia.digital/blog/o-que-muda-compra-imovel-usado-litoral-vs-planta-2026.html',
    'https://praia.digital/blog/onboarding-parceiro-imobiliario-litoral-2026.html',
    'https://praia.digital/blog/onde-fazer-compras-feirinhas-artesanato-bertioga-2026.html',
    'https://praia.digital/blog/palavras-chave-alta-intencao-imobiliarias-litoral-2026.html',
    'https://praia.digital/blog/passo-a-passo-pos-compra-imovel-matricula-itbi-2026.html',
    'https://praia.digital/blog/permuta-imovel-casamento-cuidados-outorga-2026.html',
    'https://praia.digital/blog/peruibe-bairros-imoveis-2026.html',
    'https://praia.digital/blog/planejamento-reveillon-2027-litoral-paulista.html',
    'https://praia.digital/blog/preco-m2-litoral-sp-analise-cidades-2026.html',
    'https://praia.digital/blog/predicao-mercado-imoveis-litoral-2026.html',
    'https://praia.digital/blog/pricelabs-airbnb-preco-minimo-maximo-temporada.html',
    'https://praia.digital/blog/pricelabs-imobiliarias-litoral-aumentar-receita-temporada.html',
    'https://praia.digital/blog/ptam-ia-avaliacao-mercadologica-2026.html',
    'https://praia.digital/blog/quando-vender-imovel-temporada-lucro.html',
    'https://praia.digital/blog/quanto-custa-morar-em-bertioga-2026.html',
    'https://praia.digital/blog/refinanciamento-imovel-praia-quando-vale-pena-2026.html',
    'https://praia.digital/blog/rentabilidade-imoveis-praia-2026.html',
    'https://praia.digital/blog/rentabilidade-imoveis-praia-roi-cidade-litoral-2026.html',
    'https://praia.digital/blog/rentabilidade-liquida-aluguel-temporada-litoral-paulista-2026.html',
    'https://praia.digital/blog/retorno-aluguel-temporada-indicadores-2026.html',
    'https://praia.digital/blog/riviera-sao-lourenco-portaria-impactos-2026.html',
    'https://praia.digital/blog/riviera-sao-lourenco-seguranca-infraestrutura-valorizacao-2026.html',
    'https://praia.digital/blog/santos-artigo-juridico-imoveis-2026.html',
    'https://praia.digital/blog/santos-curso-corretor-imoveis-2026.html',
    'https://praia.digital/blog/santos-curso-seo-local-imoveis-2026.html',
    'https://praia.digital/blog/santos-guia-compra-imoveis-2026.html',
    'https://praia.digital/blog/santos-juridico-imoveis-2026.html',
    'https://praia.digital/blog/sao-francisco-do-sul-bairros-imoveis-2026.html',
    'https://praia.digital/blog/sao-sebastiao-administracao-aluguel-temporada-2026.html',
    'https://praia.digital/blog/sao-sebastiao-artigo-seo-local-imoveis-2026.html',
    'https://praia.digital/blog/sao-sebastiao-seo-local-imoveis-2026.html',
    'https://praia.digital/blog/sao-vicente-aluguel-temporada-2026.html',
    'https://praia.digital/blog/sao-vicente-cidade-nautica-parque-sao-vicente-investir-2026.html',
    'https://praia.digital/blog/sao-vicente-financiamento-minha-casa-minha-vida-2026.html',
    'https://praia.digital/blog/sao-vicente-parque-bitaru-vnt-investir-2026.html',
    'https://praia.digital/blog/seguro-incendio-temporada-obrigatorio.html',
    'https://praia.digital/blog/seo-construtoras-incorporadoras-litoral-paulista-2026.html',
    'https://praia.digital/blog/simulados-gratis-creci-2026.html',
    'https://praia.digital/blog/site-imobiliaria-litoral-estrutura-converte-visitantes-leads.html',
    'https://praia.digital/blog/taxa-ocupacao-media-temporada-litoral.html',
    'https://praia.digital/blog/temporada-verao-imovel-praia.html',
    'https://praia.digital/blog/tutorial-checkin-litoral-2026.html',
    'https://praia.digital/blog/ubatuba-artigo-financiamento-imoveis-2026.html',
    'https://praia.digital/blog/ubatuba-checklist-automacao-imoveis-2026.html',
    'https://praia.digital/blog/ubatuba-curso-corretor-imoveis-2026.html',
    'https://praia.digital/blog/ubatuba-parcerias-imoveis-2026.html',
    'https://praia.digital/blog/ubatuba-praia-grande-vs-tenorio-temporada-2026.html',
    'https://praia.digital/blog/ubatuba-temporada-gestao-imoveis-2026.html',
    'https://praia.digital/blog/usucapiao-imoveis-litoral-sp-2026.html',
    'https://praia.digital/blog/vantagens-morar-bertioga.html',
    'https://praia.digital/blog/venda-imovel-heranca-2026.html',
    'https://praia.digital/blog/vender-imovel-rapido-litoral-2026.html',
    'https://praia.digital/blog/verificar-antes-comprar-vender-permutar-imovel-pessoa-casada-2026.html',
    'https://praia.digital/calculadora-rendimento-temporada-2026.html',
    'https://praia.digital/calculadoras/index.html',
    'https://praia.digital/captacao-imoveis-litoral.html',
    'https://praia.digital/cases.html',
    'https://praia.digital/cidades/bertioga-gestao-de-imovel.html',
    'https://praia.digital/cidades/bertioga-seguranca.html',
    'https://praia.digital/cidades/cananeia.html',
    'https://praia.digital/cidades/itanhaem-gestao-de-imovel.html',
    'https://praia.digital/cidades/mongagua-academia.html',
    'https://praia.digital/cidades/mongagua-gestao-de-imovel.html',
    'https://praia.digital/cidades/santos-pet-friendly.html',
    'https://praia.digital/cidades/santos-venda-rapida.html',
    'https://praia.digital/cidades/sao-vicente-academia.html',
    'https://praia.digital/cidades/sao-vicente-sauna.html',
    'https://praia.digital/conteudo-periodico/',
    'https://praia.digital/curso/apostila-completa.html',
    'https://praia.digital/dados-ocupacao-temporada-litoral-sp-2026.html',
    'https://praia.digital/demo-15min-imobiliarias-litoral-2026.html',
    'https://praia.digital/education/cursos/crm-para-corretores/index.html',
    'https://praia.digital/education/cursos/gestao-profissional-locacao/index.html',
    'https://praia.digital/education/cursos/investindo-imoveis-litoral/vendas.html',
    'https://praia.digital/education/cursos/prospeccao-para-corretores/index.html',
    'https://praia.digital/education/formacoes/captacao-imoveis.html',
    'https://praia.digital/education/formacoes/formacao-corretor-imoveis-litoral.html',
    'https://praia.digital/education/formacoes/formacao-fotografia-edicao-imoveis-temporada-2026.html',
    'https://praia.digital/education/formacoes/index.html',
    'https://praia.digital/education/index.html',
    'https://praia.digital/eventos-litoral-paulista-2026-2027/agenda-eventos-itanhaem.html',
    'https://praia.digital/eventos-litoral-paulista-2026-2027/agenda-eventos-peruibe.html',
    'https://praia.digital/eventos-litoral-paulista-2026-2027/carnaval-praia-grande.html',
    'https://praia.digital/eventos-litoral-paulista-2026-2027/festivais-verao-bertioga.html',
    'https://praia.digital/eventos-litoral-paulista-2026-2027/festivais-verao-guaruja.html',
    'https://praia.digital/eventos-litoral-paulista-2026-2027/festivais-verao-mongagua.html',
    'https://praia.digital/eventos-litoral-paulista-2026-2027/festivais-verao-sao-vicente.html',
    'https://praia.digital/eventos-litoral-paulista-2026-2027/reveillon-santos.html',
    'https://praia.digital/eventos-litoral-paulista-2026-2027/temporada-alta-guaruja.html',
    'https://praia.digital/exclusivos/comunidade-corretores-investidores.html',
    'https://praia.digital/exclusivos/rankings-exclusivos-2026.html',
    'https://praia.digital/exclusivos/relatorio-mercado-2026.html',
    'https://praia.digital/ferramentas-gratuitas/imobiliarias/checklist-documentacao-imoveis-litoral.html',
    'https://praia.digital/ferramentas/calculadora-diaria-ideal-airbnb-2026.html',
    'https://praia.digital/ferramentas/calculadora-roi-temporada.html',
    'https://praia.digital/hub/praia-grande.html',
    'https://praia.digital/ia/ia-captacao.html',
    'https://praia.digital/ia/ia-investidores.html',
    'https://praia.digital/ia/ia-marketing.html',
    'https://praia.digital/ia/ia-portais.html',
    'https://praia.digital/imoveis.html',
    'https://praia.digital/imoveis/imovel-1186.html',
    'https://praia.digital/imoveis/sobrado-caraguatatuba.html',
    'https://praia.digital/index.html',
    'https://praia.digital/landing-parcerias-imobiliarias-litoral.html',
    'https://praia.digital/litoral-prime-imoveis/bairros/santos/santos-ponta-da-praia.html',
    'https://praia.digital/mapa-inteligente.html',
    'https://praia.digital/marinas-vagas-molhadas-litoral-sp-2026.html',
    'https://praia.digital/noticias/index.html',
    'https://praia.digital/parcerias-litoral-paulista.html',
    'https://praia.digital/planos-assinatura.html',
    'https://praia.digital/politica-de-privacidade.html',
    'https://praia.digital/proposta-piloto-avaliacao-preco-imoveis-print-2026.html',
    'https://praia.digital/proposta-piloto-captacao-print-2026.html',
    'https://praia.digital/proposta-piloto-solucao-proptech-unificada-2026.html',
    'https://praia.digital/proposta-piloto-solucao-proptech-unificada-print-2026.html',
    'https://praia.digital/seo-local-bairros-litoral.html',
    'https://praia.digital/servicos/cidade-servico/praia-grande-avaliacao.html',
    'https://praia.digital/servicos/cidade-servico/santos-captacao.html',
    'https://praia.digital/servicos/venda-imovel.html',
    'https://praia.digital/solucoes/',
    'https://praia.digital/solucoes/demo-ia-imobiliarias.html',
    'https://praia.digital/solucoes/hermes-agents.html',
    'https://praia.digital/termos-uso.html',
    'https://praia.digital/terrenos-marinha-taxa-aforamento-litoral-sp-2026.html',
    'https://praia.digital/top5-leads-hoje.html'
}

def pillar_for(url):
    for rx, p in PILLARS:
        if rx.search(url):
            return BASE + p
    return None

canon_re = re.compile(r'<link rel="canonical" href="[^"]*">', re.I)
changed = 0
total = 0
for root, dirs, files in os.walk('blog'):
    for f in files:
        if not f.endswith('.html'):
            continue
        path = os.path.join(root, f)
        url = BASE + path.replace(os.sep, '/')
        if url in KEEP:
            continue
        pillar = pillar_for(url)
        if not pillar:
            continue
        total += 1
        html = open(path, encoding='utf-8', errors='replace').read()
        tag = f'<link rel="canonical" href="{pillar}">'
        if canon_re.search(html):
            new = canon_re.sub(tag, html, count=1)
        elif '</head>' in html:
            new = html.replace('</head>', '  ' + tag + '\n</head>', 1)
        else:
            continue
        if new != html:
            open(path, 'w', encoding='utf-8').write(new)
            changed += 1
print(f'blog: {total} posts finos elegiveis, {changed} canonicals atualizados')
